# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: nvidia_ace.a2f_authoring.v1.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from nvidia_ace.audio import v1_pb2 as nvidia__ace_dot_audio_dot_v1__pb2
from nvidia_ace.a2f import v1_pb2 as nvidia__ace_dot_a2f_dot_v1__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n!nvidia_ace.a2f_authoring.v1.proto\x12\x1bnvidia_ace.a2f_authoring.v1\x1a\x19nvidia_ace.audio.v1.proto\x1a\x17nvidia_ace.a2f.v1.proto\"T\n\tAudioClip\x12\x36\n\x0c\x61udio_header\x18\x01 \x01(\x0b\x32 .nvidia_ace.audio.v1.AudioHeader\x12\x0f\n\x07\x63ontent\x18\x02 \x01(\x0c\"B\n\x0f\x41udioClipHandle\x12\x15\n\raudio_clip_id\x18\x01 \x01(\t\x12\x18\n\x10\x62lendshape_names\x18\x02 \x03(\t\"\x9f\x03\n\x0f\x46\x61\x63\x65PoseRequest\x12\x12\n\naudio_hash\x18\x01 \x01(\t\x12_\n\x12preferred_emotions\x18\x02 \x03(\x0b\x32\x43.nvidia_ace.a2f_authoring.v1.FacePoseRequest.PreferredEmotionsEntry\x12\x12\n\ntime_stamp\x18\x03 \x01(\x02\x12\x36\n\x0b\x66\x61\x63\x65_params\x18\x04 \x01(\x0b\x32!.nvidia_ace.a2f.v1.FaceParameters\x12M\n\x11\x65motion_pp_params\x18\x05 \x01(\x0b\x32\x32.nvidia_ace.a2f.v1.EmotionPostProcessingParameters\x12\x42\n\x11\x62lendshape_params\x18\x06 \x01(\x0b\x32\'.nvidia_ace.a2f.v1.BlendShapeParameters\x1a\x38\n\x16PreferredEmotionsEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\x02:\x02\x38\x01\"\xb6\x01\n\x0e\x42lendShapeData\x12\x13\n\x0b\x62lendshapes\x18\x01 \x03(\x02\x12\x11\n\ttime_code\x18\x02 \x01(\x02\x12K\n\x08\x65motions\x18\x03 \x03(\x0b\x32\x39.nvidia_ace.a2f_authoring.v1.BlendShapeData.EmotionsEntry\x1a/\n\rEmotionsEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\x02:\x02\x38\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'nvidia_ace.a2f_authoring.v1_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_FACEPOSEREQUEST_PREFERREDEMOTIONSENTRY']._loaded_options = None
  _globals['_FACEPOSEREQUEST_PREFERREDEMOTIONSENTRY']._serialized_options = b'8\001'
  _globals['_BLENDSHAPEDATA_EMOTIONSENTRY']._loaded_options = None
  _globals['_BLENDSHAPEDATA_EMOTIONSENTRY']._serialized_options = b'8\001'
  _globals['_AUDIOCLIP']._serialized_start=118
  _globals['_AUDIOCLIP']._serialized_end=202
  _globals['_AUDIOCLIPHANDLE']._serialized_start=204
  _globals['_AUDIOCLIPHANDLE']._serialized_end=270
  _globals['_FACEPOSEREQUEST']._serialized_start=273
  _globals['_FACEPOSEREQUEST']._serialized_end=688
  _globals['_FACEPOSEREQUEST_PREFERREDEMOTIONSENTRY']._serialized_start=632
  _globals['_FACEPOSEREQUEST_PREFERREDEMOTIONSENTRY']._serialized_end=688
  _globals['_BLENDSHAPEDATA']._serialized_start=691
  _globals['_BLENDSHAPEDATA']._serialized_end=873
  _globals['_BLENDSHAPEDATA_EMOTIONSENTRY']._serialized_start=826
  _globals['_BLENDSHAPEDATA_EMOTIONSENTRY']._serialized_end=873
# @@protoc_insertion_point(module_scope)
