# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: nvidia_ace.emotion_aggregate.v1.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from nvidia_ace.emotion_with_timecode import v1_pb2 as nvidia__ace_dot_emotion__with__timecode_dot_v1__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n%nvidia_ace.emotion_aggregate.v1.proto\x12\x1fnvidia_ace.emotion_aggregate.v1\x1a)nvidia_ace.emotion_with_timecode.v1.proto\"\x89\x02\n\x10\x45motionAggregate\x12P\n\x0einput_emotions\x18\x01 \x03(\x0b\x32\x38.nvidia_ace.emotion_with_timecode.v1.EmotionWithTimeCode\x12L\n\na2e_output\x18\x02 \x03(\x0b\x32\x38.nvidia_ace.emotion_with_timecode.v1.EmotionWithTimeCode\x12U\n\x13\x61\x32\x66_smoothed_output\x18\x03 \x03(\x0b\x32\x38.nvidia_ace.emotion_with_timecode.v1.EmotionWithTimeCodeb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'nvidia_ace.emotion_aggregate.v1_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_EMOTIONAGGREGATE']._serialized_start=118
  _globals['_EMOTIONAGGREGATE']._serialized_end=383
# @@protoc_insertion_point(module_scope)
