a2e:
  post_processing_params:
    emotion_contrast: 1.0
    emotion_strength: 0.6000000238418579
    enable_preferred_emotion: true
    live_blend_coef: 0.699999988079071
    max_emotions: 6
    preferred_emotion_strength: 1.0
  preferred_emotions:
    amazement: 0.0
    anger: 1.0
    cheekiness: 0.0
    disgust: 0.0
    fear: 0.0
    grief: 0.0
    joy: 0.0
    outofbreath: 0.0
    pain: 0.0
    sadness: 0.0
a2f:
  blendshape_params:
    weight_multipliers:
      BrowDownLeft: 1.0
      BrowDownRight: 1.0
      BrowInnerUp: 1.0
      BrowOuterUpLeft: 1.0
      BrowOuterUpRight: 1.0
      CheekPuff: 1.0
      CheekSquintLeft: 1.0
      CheekSquintRight: 1.0
      EyeBlinkLeft: 1.0
      EyeBlinkRight: 1.0
      EyeLookDownLeft: 1.0
      EyeLookDownRight: 1.0
      EyeLookInLeft: 1.0
      EyeLookInRight: 1.0
      EyeLookOutLeft: 1.0
      EyeLookOutRight: 1.0
      EyeLookUpLeft: 1.0
      EyeLookUpRight: 1.0
      EyeSquintLeft: 1.0
      EyeSquintRight: 1.0
      EyeWideLeft: 1.0
      EyeWideRight: 1.0
      JawForward: 1.0
      JawLeft: 1.0
      JawOpen: 1.0
      JawRight: 1.0
      MouthClose: 1.0
      MouthDimpleLeft: 1.0
      MouthDimpleRight: 1.0
      MouthFrownLeft: 1.0
      MouthFrownRight: 1.0
      MouthFunnel: 1.0
      MouthLeft: 1.0
      MouthLowerDownLeft: 1.0
      MouthLowerDownRight: 1.0
      MouthPressLeft: 1.0
      MouthPressRight: 1.0
      MouthPucker: 1.0
      MouthRight: 1.0
      MouthRollLower: 1.0
      MouthRollUpper: 1.0
      MouthShrugLower: 1.0
      MouthShrugUpper: 1.0
      MouthSmileLeft: 1.0
      MouthSmileRight: 1.0
      MouthStretchLeft: 1.0
      MouthStretchRight: 1.0
      MouthUpperUpLeft: 1.0
      MouthUpperUpRight: 1.0
      NoseSneerLeft: 1.0
      NoseSneerRight: 1.0
      TongueOut: 1.0
    weight_offsets:
      BrowDownLeft: 0.0
      BrowDownRight: 0.0
      BrowInnerUp: 0.0
      BrowOuterUpLeft: 0.0
      BrowOuterUpRight: 0.0
      CheekPuff: 0.0
      CheekSquintLeft: 0.0
      CheekSquintRight: 0.0
      EyeBlinkLeft: 0.0
      EyeBlinkRight: 0.0
      EyeLookDownLeft: 0.0
      EyeLookDownRight: 0.0
      EyeLookInLeft: 0.0
      EyeLookInRight: 0.0
      EyeLookOutLeft: 0.0
      EyeLookOutRight: 0.0
      EyeLookUpLeft: 0.0
      EyeLookUpRight: 0.0
      EyeSquintLeft: 0.0
      EyeSquintRight: 0.0
      EyeWideLeft: 0.0
      EyeWideRight: 0.0
      JawForward: 0.0
      JawLeft: 0.0
      JawOpen: 0.0
      JawRight: 0.0
      MouthClose: 0.0
      MouthDimpleLeft: 0.0
      MouthDimpleRight: 0.0
      MouthFrownLeft: 0.0
      MouthFrownRight: 0.0
      MouthFunnel: 0.0
      MouthLeft: 0.0
      MouthLowerDownLeft: 0.0
      MouthLowerDownRight: 0.0
      MouthPressLeft: 0.0
      MouthPressRight: 0.0
      MouthPucker: 0.0
      MouthRight: 0.0
      MouthRollLower: 0.0
      MouthRollUpper: 0.0
      MouthShrugLower: 0.0
      MouthShrugUpper: 0.0
      MouthSmileLeft: 0.0
      MouthSmileRight: 0.0
      MouthStretchLeft: 0.0
      MouthStretchRight: 0.0
      MouthUpperUpLeft: 0.0
      MouthUpperUpRight: 0.0
      NoseSneerLeft: 0.0
      NoseSneerRight: 0.0
      TongueOut: 0.0
  face_params:
    eyelid_offset: 0.0
    face_mask_level: 0.6000000238418579
    face_mask_softness: 0.008500000461935997
    lip_close_offset: -0.019999999552965164
    lower_face_smoothing: 0.006000000052154064
    lower_face_strength: 1.2000000476837158
    skin_strength: 1.0
    upper_face_smoothing: 0.0010000000474974513
    upper_face_strength: 1.0
  tongue_params: {}
