# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: nvidia_ace.status.v1.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1anvidia_ace.status.v1.proto\x12\x14nvidia_ace.status.v1\"\x81\x01\n\x06Status\x12/\n\x04\x63ode\x18\x01 \x01(\x0e\x32!.nvidia_ace.status.v1.Status.Code\x12\x0f\n\x07message\x18\x02 \x01(\t\"5\n\x04\x43ode\x12\x0b\n\x07SUCCESS\x10\x00\x12\x08\n\x04INFO\x10\x01\x12\x0b\n\x07WARNING\x10\x02\x12\t\n\x05\x45RROR\x10\x03\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'nvidia_ace.status.v1_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_STATUS']._serialized_start=53
  _globals['_STATUS']._serialized_end=182
  _globals['_STATUS_CODE']._serialized_start=129
  _globals['_STATUS_CODE']._serialized_end=182
# @@protoc_insertion_point(module_scope)
