# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: nvidia_ace.services.a2f_authoring.v1.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from nvidia_ace.a2f_authoring import v1_pb2 as nvidia__ace_dot_a2f__authoring_dot_v1__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n*nvidia_ace.services.a2f_authoring.v1.proto\x12$nvidia_ace.services.a2f_authoring.v1\x1a!nvidia_ace.a2f_authoring.v1.proto2\xf2\x01\n\x13\x41\x32\x46\x41uthoringService\x12i\n\x0fUploadAudioClip\x12&.nvidia_ace.a2f_authoring.v1.AudioClip\x1a,.nvidia_ace.a2f_authoring.v1.AudioClipHandle\"\x00\x12p\n\x11GetAvatarFacePose\x12,.nvidia_ace.a2f_authoring.v1.FacePoseRequest\x1a+.nvidia_ace.a2f_authoring.v1.BlendShapeData\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'nvidia_ace.services.a2f_authoring.v1_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_A2FAUTHORINGSERVICE']._serialized_start=120
  _globals['_A2FAUTHORINGSERVICE']._serialized_end=362
# @@protoc_insertion_point(module_scope)
