# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: nvidia_ace.audio.v1.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x19nvidia_ace.audio.v1.proto\x12\x13nvidia_ace.audio.v1\"\xc2\x01\n\x0b\x41udioHeader\x12\x42\n\x0c\x61udio_format\x18\x01 \x01(\x0e\x32,.nvidia_ace.audio.v1.AudioHeader.AudioFormat\x12\x15\n\rchannel_count\x18\x02 \x01(\r\x12\x1a\n\x12samples_per_second\x18\x03 \x01(\r\x12\x17\n\x0f\x62its_per_sample\x18\x04 \x01(\r\"#\n\x0b\x41udioFormat\x12\x14\n\x10\x41UDIO_FORMAT_PCM\x10\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'nvidia_ace.audio.v1_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_AUDIOHEADER']._serialized_start=51
  _globals['_AUDIOHEADER']._serialized_end=245
  _globals['_AUDIOHEADER_AUDIOFORMAT']._serialized_start=210
  _globals['_AUDIOHEADER_AUDIOFORMAT']._serialized_end=245
# @@protoc_insertion_point(module_scope)
