# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from nvidia_ace.services.a2x_export_config import v1_pb2 as nvidia__ace_dot_services_dot_a2x__export__config_dot_v1__pb2

GRPC_GENERATED_VERSION = '1.64.1'
GRPC_VERSION = grpc.__version__
EXPECTED_ERROR_RELEASE = '1.65.0'
SCHEDULED_RELEASE_DATE = 'June 25, 2024'
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    warnings.warn(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in nvidia_ace.services.a2x_export_config.v1_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
        + f' This warning will become an error in {EXPECTED_ERROR_RELEASE},'
        + f' scheduled for release on {SCHEDULED_RELEASE_DATE}.',
        RuntimeWarning
    )


class A2XExportConfigServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetConfigs = channel.unary_stream(
                '/nvidia_ace.services.a2x_export_config.v1.A2XExportConfigService/GetConfigs',
                request_serializer=nvidia__ace_dot_services_dot_a2x__export__config_dot_v1__pb2.ConfigsTypeRequest.SerializeToString,
                response_deserializer=nvidia__ace_dot_services_dot_a2x__export__config_dot_v1__pb2.A2XConfig.FromString,
                _registered_method=True)


class A2XExportConfigServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetConfigs(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_A2XExportConfigServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetConfigs': grpc.unary_stream_rpc_method_handler(
                    servicer.GetConfigs,
                    request_deserializer=nvidia__ace_dot_services_dot_a2x__export__config_dot_v1__pb2.ConfigsTypeRequest.FromString,
                    response_serializer=nvidia__ace_dot_services_dot_a2x__export__config_dot_v1__pb2.A2XConfig.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'nvidia_ace.services.a2x_export_config.v1.A2XExportConfigService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('nvidia_ace.services.a2x_export_config.v1.A2XExportConfigService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class A2XExportConfigService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetConfigs(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/nvidia_ace.services.a2x_export_config.v1.A2XExportConfigService/GetConfigs',
            nvidia__ace_dot_services_dot_a2x__export__config_dot_v1__pb2.ConfigsTypeRequest.SerializeToString,
            nvidia__ace_dot_services_dot_a2x__export__config_dot_v1__pb2.A2XConfig.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
