// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: nvidia_ace.services.animation_controller.v1.proto

#ifndef GRPC_MOCK_nvidia_5face_2eservices_2eanimation_5fcontroller_2ev1_2eproto__INCLUDED
#define GRPC_MOCK_nvidia_5face_2eservices_2eanimation_5fcontroller_2ev1_2eproto__INCLUDED

#include "nvidia_ace.services.animation_controller.v1.pb.h"
#include "nvidia_ace.services.animation_controller.v1.grpc.pb.h"

#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/sync_stream.h>
#include <gmock/gmock.h>
namespace nvidia_ace {
namespace services {
namespace animation_controller {
namespace v1 {

class MockAnimationControllerServiceStub : public AnimationControllerService::StubInterface {
 public:
  MOCK_METHOD3(RequestAnimationIds, ::grpc::Status(::grpc::ClientContext* context, const ::google::protobuf::Empty& request, ::nvidia_ace::services::animation_controller::v1::AnimationIdsOrStatus* response));
  MOCK_METHOD3(AsyncRequestAnimationIdsRaw, ::grpc::ClientAsyncResponseReaderInterface< ::nvidia_ace::services::animation_controller::v1::AnimationIdsOrStatus>*(::grpc::ClientContext* context, const ::google::protobuf::Empty& request, ::grpc::CompletionQueue* cq));
  MOCK_METHOD3(PrepareAsyncRequestAnimationIdsRaw, ::grpc::ClientAsyncResponseReaderInterface< ::nvidia_ace::services::animation_controller::v1::AnimationIdsOrStatus>*(::grpc::ClientContext* context, const ::google::protobuf::Empty& request, ::grpc::CompletionQueue* cq));
  MOCK_METHOD2(PullAnimationDataStreamRaw, ::grpc::ClientReaderInterface< ::nvidia_ace::animation_data::v1::AnimationDataStream>*(::grpc::ClientContext* context, const ::nvidia_ace::animation_id::v1::AnimationIds& request));
  MOCK_METHOD4(AsyncPullAnimationDataStreamRaw, ::grpc::ClientAsyncReaderInterface< ::nvidia_ace::animation_data::v1::AnimationDataStream>*(::grpc::ClientContext* context, const ::nvidia_ace::animation_id::v1::AnimationIds& request, ::grpc::CompletionQueue* cq, void* tag));
  MOCK_METHOD3(PrepareAsyncPullAnimationDataStreamRaw, ::grpc::ClientAsyncReaderInterface< ::nvidia_ace::animation_data::v1::AnimationDataStream>*(::grpc::ClientContext* context, const ::nvidia_ace::animation_id::v1::AnimationIds& request, ::grpc::CompletionQueue* cq));
  MOCK_METHOD2(PushAudioStreamRaw, ::grpc::ClientWriterInterface< ::nvidia_ace::a2f::v1::AudioStream>*(::grpc::ClientContext* context, ::nvidia_ace::status::v1::Status* response));
  MOCK_METHOD4(AsyncPushAudioStreamRaw, ::grpc::ClientAsyncWriterInterface< ::nvidia_ace::a2f::v1::AudioStream>*(::grpc::ClientContext* context, ::nvidia_ace::status::v1::Status* response, ::grpc::CompletionQueue* cq, void* tag));
  MOCK_METHOD3(PrepareAsyncPushAudioStreamRaw, ::grpc::ClientAsyncWriterInterface< ::nvidia_ace::a2f::v1::AudioStream>*(::grpc::ClientContext* context, ::nvidia_ace::status::v1::Status* response, ::grpc::CompletionQueue* cq));
  MOCK_METHOD2(UpdateAnimationGraphVariableRaw, ::grpc::ClientWriterInterface< ::nvidia_ace::services::animation_controller::v1::AnimationGraphRequest>*(::grpc::ClientContext* context, ::nvidia_ace::status::v1::Status* response));
  MOCK_METHOD4(AsyncUpdateAnimationGraphVariableRaw, ::grpc::ClientAsyncWriterInterface< ::nvidia_ace::services::animation_controller::v1::AnimationGraphRequest>*(::grpc::ClientContext* context, ::nvidia_ace::status::v1::Status* response, ::grpc::CompletionQueue* cq, void* tag));
  MOCK_METHOD3(PrepareAsyncUpdateAnimationGraphVariableRaw, ::grpc::ClientAsyncWriterInterface< ::nvidia_ace::services::animation_controller::v1::AnimationGraphRequest>*(::grpc::ClientContext* context, ::nvidia_ace::status::v1::Status* response, ::grpc::CompletionQueue* cq));
};

}  // namespace v1
}  // namespace animation_controller
}  // namespace services
}  // namespace nvidia_ace


#endif  // GRPC_MOCK_nvidia_5face_2eservices_2eanimation_5fcontroller_2ev1_2eproto__INCLUDED
