// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: nvidia_ace.services.a2x_export_config.v1.proto

#ifndef GRPC_MOCK_nvidia_5face_2eservices_2ea2x_5fexport_5fconfig_2ev1_2eproto__INCLUDED
#define GRPC_MOCK_nvidia_5face_2eservices_2ea2x_5fexport_5fconfig_2ev1_2eproto__INCLUDED

#include "nvidia_ace.services.a2x_export_config.v1.pb.h"
#include "nvidia_ace.services.a2x_export_config.v1.grpc.pb.h"

#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/sync_stream.h>
#include <gmock/gmock.h>
namespace nvidia_ace {
namespace services {
namespace a2x_export_config {
namespace v1 {

class MockA2XExportConfigServiceStub : public A2XExportConfigService::StubInterface {
 public:
  MOCK_METHOD2(GetConfigsRaw, ::grpc::ClientReaderInterface< ::nvidia_ace::services::a2x_export_config::v1::A2XConfig>*(::grpc::ClientContext* context, const ::nvidia_ace::services::a2x_export_config::v1::ConfigsTypeRequest& request));
  MOCK_METHOD4(AsyncGetConfigsRaw, ::grpc::ClientAsyncReaderInterface< ::nvidia_ace::services::a2x_export_config::v1::A2XConfig>*(::grpc::ClientContext* context, const ::nvidia_ace::services::a2x_export_config::v1::ConfigsTypeRequest& request, ::grpc::CompletionQueue* cq, void* tag));
  MOCK_METHOD3(PrepareAsyncGetConfigsRaw, ::grpc::ClientAsyncReaderInterface< ::nvidia_ace::services::a2x_export_config::v1::A2XConfig>*(::grpc::ClientContext* context, const ::nvidia_ace::services::a2x_export_config::v1::ConfigsTypeRequest& request, ::grpc::CompletionQueue* cq));
};

}  // namespace v1
}  // namespace a2x_export_config
}  // namespace services
}  // namespace nvidia_ace


#endif  // GRPC_MOCK_nvidia_5face_2eservices_2ea2x_5fexport_5fconfig_2ev1_2eproto__INCLUDED
