// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: nvidia_ace.audio.v1.proto
// Protobuf C++ Version: 5.26.0

#ifndef GOOGLE_PROTOBUF_INCLUDED_nvidia_5face_2eaudio_2ev1_2eproto_2epb_2eh
#define GOOGLE_PROTOBUF_INCLUDED_nvidia_5face_2eaudio_2ev1_2eproto_2epb_2eh

#include <limits>
#include <string>
#include <type_traits>
#include <utility>

#include "google/protobuf/port_def.inc"
#if PROTOBUF_VERSION != 5026000
#error "Protobuf C++ gencode is built with an incompatible version of"
#error "Protobuf C++ headers/runtime. See"
#error "https://protobuf.dev/support/cross-version-runtime-guarantee/#cpp"
#endif
#include "google/protobuf/port_undef.inc"
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/arena.h"
#include "google/protobuf/arenastring.h"
#include "google/protobuf/generated_message_tctable_decl.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/metadata_lite.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/message.h"
#include "google/protobuf/repeated_field.h"  // IWYU pragma: export
#include "google/protobuf/extension_set.h"  // IWYU pragma: export
#include "google/protobuf/generated_enum_reflection.h"
#include "google/protobuf/unknown_field_set.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"

#define PROTOBUF_INTERNAL_EXPORT_nvidia_5face_2eaudio_2ev1_2eproto

namespace google {
namespace protobuf {
namespace internal {
class AnyMetadata;
}  // namespace internal
}  // namespace protobuf
}  // namespace google

// Internal implementation detail -- do not use these members.
struct TableStruct_nvidia_5face_2eaudio_2ev1_2eproto {
  static const ::uint32_t offsets[];
};
extern const ::google::protobuf::internal::DescriptorTable
    descriptor_table_nvidia_5face_2eaudio_2ev1_2eproto;
namespace nvidia_ace {
namespace audio {
namespace v1 {
class AudioHeader;
struct AudioHeaderDefaultTypeInternal;
extern AudioHeaderDefaultTypeInternal _AudioHeader_default_instance_;
}  // namespace v1
}  // namespace audio
}  // namespace nvidia_ace
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google

namespace nvidia_ace {
namespace audio {
namespace v1 {
enum AudioHeader_AudioFormat : int {
  AudioHeader_AudioFormat_AUDIO_FORMAT_PCM = 0,
  AudioHeader_AudioFormat_AudioHeader_AudioFormat_INT_MIN_SENTINEL_DO_NOT_USE_ =
      std::numeric_limits<::int32_t>::min(),
  AudioHeader_AudioFormat_AudioHeader_AudioFormat_INT_MAX_SENTINEL_DO_NOT_USE_ =
      std::numeric_limits<::int32_t>::max(),
};

bool AudioHeader_AudioFormat_IsValid(int value);
extern const uint32_t AudioHeader_AudioFormat_internal_data_[];
constexpr AudioHeader_AudioFormat AudioHeader_AudioFormat_AudioFormat_MIN = static_cast<AudioHeader_AudioFormat>(0);
constexpr AudioHeader_AudioFormat AudioHeader_AudioFormat_AudioFormat_MAX = static_cast<AudioHeader_AudioFormat>(0);
constexpr int AudioHeader_AudioFormat_AudioFormat_ARRAYSIZE = 0 + 1;
const ::google::protobuf::EnumDescriptor*
AudioHeader_AudioFormat_descriptor();
template <typename T>
const std::string& AudioHeader_AudioFormat_Name(T value) {
  static_assert(std::is_same<T, AudioHeader_AudioFormat>::value ||
                    std::is_integral<T>::value,
                "Incorrect type passed to AudioFormat_Name().");
  return AudioHeader_AudioFormat_Name(static_cast<AudioHeader_AudioFormat>(value));
}
template <>
inline const std::string& AudioHeader_AudioFormat_Name(AudioHeader_AudioFormat value) {
  return ::google::protobuf::internal::NameOfDenseEnum<AudioHeader_AudioFormat_descriptor,
                                                 0, 0>(
      static_cast<int>(value));
}
inline bool AudioHeader_AudioFormat_Parse(absl::string_view name, AudioHeader_AudioFormat* value) {
  return ::google::protobuf::internal::ParseNamedEnum<AudioHeader_AudioFormat>(
      AudioHeader_AudioFormat_descriptor(), name, value);
}

// ===================================================================


// -------------------------------------------------------------------

class AudioHeader final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:nvidia_ace.audio.v1.AudioHeader) */ {
 public:
  inline AudioHeader() : AudioHeader(nullptr) {}
  ~AudioHeader() override;
  template <typename = void>
  explicit PROTOBUF_CONSTEXPR AudioHeader(
      ::google::protobuf::internal::ConstantInitialized);

  inline AudioHeader(const AudioHeader& from) : AudioHeader(nullptr, from) {}
  inline AudioHeader(AudioHeader&& from) noexcept
      : AudioHeader(nullptr, std::move(from)) {}
  inline AudioHeader& operator=(const AudioHeader& from) {
    CopyFrom(from);
    return *this;
  }
  inline AudioHeader& operator=(AudioHeader&& from) noexcept {
    if (this == &from) return *this;
    if (GetArena() == from.GetArena()
#ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetArena() != nullptr
#endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const AudioHeader& default_instance() {
    return *internal_default_instance();
  }
  static inline const AudioHeader* internal_default_instance() {
    return reinterpret_cast<const AudioHeader*>(
        &_AudioHeader_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 0;
  friend void swap(AudioHeader& a, AudioHeader& b) { a.Swap(&b); }
  inline void Swap(AudioHeader* other) {
    if (other == this) return;
#ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetArena() != nullptr && GetArena() == other->GetArena()) {
#else   // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetArena() == other->GetArena()) {
#endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(AudioHeader* other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  AudioHeader* New(::google::protobuf::Arena* arena = nullptr) const final {
    return ::google::protobuf::Message::DefaultConstruct<AudioHeader>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const AudioHeader& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const AudioHeader& from) { AudioHeader::MergeImpl(*this, from); }

  private:
  static void MergeImpl(
      ::google::protobuf::MessageLite& to_msg,
      const ::google::protobuf::MessageLite& from_msg);

  public:
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  ::size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::google::protobuf::internal::ParseContext* ctx) final;
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* arena);
  void SharedDtor();
  void InternalSwap(AudioHeader* other);
 private:
  friend class ::google::protobuf::internal::AnyMetadata;
  static ::absl::string_view FullMessageName() { return "nvidia_ace.audio.v1.AudioHeader"; }

 protected:
  explicit AudioHeader(::google::protobuf::Arena* arena);
  AudioHeader(::google::protobuf::Arena* arena, const AudioHeader& from);
  AudioHeader(::google::protobuf::Arena* arena, AudioHeader&& from) noexcept
      : AudioHeader(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::MessageLite::ClassData* GetClassData()
      const final;

 public:
  ::google::protobuf::Metadata GetMetadata() const final;
  // nested types ----------------------------------------------------
  using AudioFormat = AudioHeader_AudioFormat;
  static constexpr AudioFormat AUDIO_FORMAT_PCM = AudioHeader_AudioFormat_AUDIO_FORMAT_PCM;
  static inline bool AudioFormat_IsValid(int value) {
    return AudioHeader_AudioFormat_IsValid(value);
  }
  static constexpr AudioFormat AudioFormat_MIN = AudioHeader_AudioFormat_AudioFormat_MIN;
  static constexpr AudioFormat AudioFormat_MAX = AudioHeader_AudioFormat_AudioFormat_MAX;
  static constexpr int AudioFormat_ARRAYSIZE = AudioHeader_AudioFormat_AudioFormat_ARRAYSIZE;
  static inline const ::google::protobuf::EnumDescriptor* AudioFormat_descriptor() {
    return AudioHeader_AudioFormat_descriptor();
  }
  template <typename T>
  static inline const std::string& AudioFormat_Name(T value) {
    return AudioHeader_AudioFormat_Name(value);
  }
  static inline bool AudioFormat_Parse(absl::string_view name, AudioFormat* value) {
    return AudioHeader_AudioFormat_Parse(name, value);
  }

  // accessors -------------------------------------------------------
  enum : int {
    kAudioFormatFieldNumber = 1,
    kChannelCountFieldNumber = 2,
    kSamplesPerSecondFieldNumber = 3,
    kBitsPerSampleFieldNumber = 4,
  };
  // .nvidia_ace.audio.v1.AudioHeader.AudioFormat audio_format = 1;
  void clear_audio_format() ;
  ::nvidia_ace::audio::v1::AudioHeader_AudioFormat audio_format() const;
  void set_audio_format(::nvidia_ace::audio::v1::AudioHeader_AudioFormat value);

  private:
  ::nvidia_ace::audio::v1::AudioHeader_AudioFormat _internal_audio_format() const;
  void _internal_set_audio_format(::nvidia_ace::audio::v1::AudioHeader_AudioFormat value);

  public:
  // uint32 channel_count = 2;
  void clear_channel_count() ;
  ::uint32_t channel_count() const;
  void set_channel_count(::uint32_t value);

  private:
  ::uint32_t _internal_channel_count() const;
  void _internal_set_channel_count(::uint32_t value);

  public:
  // uint32 samples_per_second = 3;
  void clear_samples_per_second() ;
  ::uint32_t samples_per_second() const;
  void set_samples_per_second(::uint32_t value);

  private:
  ::uint32_t _internal_samples_per_second() const;
  void _internal_set_samples_per_second(::uint32_t value);

  public:
  // uint32 bits_per_sample = 4;
  void clear_bits_per_sample() ;
  ::uint32_t bits_per_sample() const;
  void set_bits_per_sample(::uint32_t value);

  private:
  ::uint32_t _internal_bits_per_sample() const;
  void _internal_set_bits_per_sample(::uint32_t value);

  public:
  // @@protoc_insertion_point(class_scope:nvidia_ace.audio.v1.AudioHeader)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<
      2, 4, 0,
      0, 2>
      _table_;
  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(
        ::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena);
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena, const Impl_& from);
    int audio_format_;
    ::uint32_t channel_count_;
    ::uint32_t samples_per_second_;
    ::uint32_t bits_per_sample_;
    mutable ::google::protobuf::internal::CachedSize _cached_size_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_nvidia_5face_2eaudio_2ev1_2eproto;
};

// ===================================================================




// ===================================================================


#ifdef __GNUC__
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// -------------------------------------------------------------------

// AudioHeader

// .nvidia_ace.audio.v1.AudioHeader.AudioFormat audio_format = 1;
inline void AudioHeader::clear_audio_format() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  _impl_.audio_format_ = 0;
}
inline ::nvidia_ace::audio::v1::AudioHeader_AudioFormat AudioHeader::audio_format() const {
  // @@protoc_insertion_point(field_get:nvidia_ace.audio.v1.AudioHeader.audio_format)
  return _internal_audio_format();
}
inline void AudioHeader::set_audio_format(::nvidia_ace::audio::v1::AudioHeader_AudioFormat value) {
  _internal_set_audio_format(value);
  // @@protoc_insertion_point(field_set:nvidia_ace.audio.v1.AudioHeader.audio_format)
}
inline ::nvidia_ace::audio::v1::AudioHeader_AudioFormat AudioHeader::_internal_audio_format() const {
  PROTOBUF_TSAN_READ(&_impl_._tsan_detect_race);
  return static_cast<::nvidia_ace::audio::v1::AudioHeader_AudioFormat>(_impl_.audio_format_);
}
inline void AudioHeader::_internal_set_audio_format(::nvidia_ace::audio::v1::AudioHeader_AudioFormat value) {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  _impl_.audio_format_ = value;
}

// uint32 channel_count = 2;
inline void AudioHeader::clear_channel_count() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  _impl_.channel_count_ = 0u;
}
inline ::uint32_t AudioHeader::channel_count() const {
  // @@protoc_insertion_point(field_get:nvidia_ace.audio.v1.AudioHeader.channel_count)
  return _internal_channel_count();
}
inline void AudioHeader::set_channel_count(::uint32_t value) {
  _internal_set_channel_count(value);
  // @@protoc_insertion_point(field_set:nvidia_ace.audio.v1.AudioHeader.channel_count)
}
inline ::uint32_t AudioHeader::_internal_channel_count() const {
  PROTOBUF_TSAN_READ(&_impl_._tsan_detect_race);
  return _impl_.channel_count_;
}
inline void AudioHeader::_internal_set_channel_count(::uint32_t value) {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  _impl_.channel_count_ = value;
}

// uint32 samples_per_second = 3;
inline void AudioHeader::clear_samples_per_second() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  _impl_.samples_per_second_ = 0u;
}
inline ::uint32_t AudioHeader::samples_per_second() const {
  // @@protoc_insertion_point(field_get:nvidia_ace.audio.v1.AudioHeader.samples_per_second)
  return _internal_samples_per_second();
}
inline void AudioHeader::set_samples_per_second(::uint32_t value) {
  _internal_set_samples_per_second(value);
  // @@protoc_insertion_point(field_set:nvidia_ace.audio.v1.AudioHeader.samples_per_second)
}
inline ::uint32_t AudioHeader::_internal_samples_per_second() const {
  PROTOBUF_TSAN_READ(&_impl_._tsan_detect_race);
  return _impl_.samples_per_second_;
}
inline void AudioHeader::_internal_set_samples_per_second(::uint32_t value) {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  _impl_.samples_per_second_ = value;
}

// uint32 bits_per_sample = 4;
inline void AudioHeader::clear_bits_per_sample() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  _impl_.bits_per_sample_ = 0u;
}
inline ::uint32_t AudioHeader::bits_per_sample() const {
  // @@protoc_insertion_point(field_get:nvidia_ace.audio.v1.AudioHeader.bits_per_sample)
  return _internal_bits_per_sample();
}
inline void AudioHeader::set_bits_per_sample(::uint32_t value) {
  _internal_set_bits_per_sample(value);
  // @@protoc_insertion_point(field_set:nvidia_ace.audio.v1.AudioHeader.bits_per_sample)
}
inline ::uint32_t AudioHeader::_internal_bits_per_sample() const {
  PROTOBUF_TSAN_READ(&_impl_._tsan_detect_race);
  return _impl_.bits_per_sample_;
}
inline void AudioHeader::_internal_set_bits_per_sample(::uint32_t value) {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  _impl_.bits_per_sample_ = value;
}

#ifdef __GNUC__
#pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)
}  // namespace v1
}  // namespace audio
}  // namespace nvidia_ace


namespace google {
namespace protobuf {

template <>
struct is_proto_enum<::nvidia_ace::audio::v1::AudioHeader_AudioFormat> : std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor<::nvidia_ace::audio::v1::AudioHeader_AudioFormat>() {
  return ::nvidia_ace::audio::v1::AudioHeader_AudioFormat_descriptor();
}

}  // namespace protobuf
}  // namespace google

// @@protoc_insertion_point(global_scope)

#include "google/protobuf/port_undef.inc"

#endif  // GOOGLE_PROTOBUF_INCLUDED_nvidia_5face_2eaudio_2ev1_2eproto_2epb_2eh
