// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: nvidia_ace.services.a2x_export_config.v1.proto
// Protobuf C++ Version: 5.26.0

#include "nvidia_ace.services.a2x_export_config.v1.pb.h"

#include <algorithm>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/descriptor.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/reflection_ops.h"
#include "google/protobuf/wire_format.h"
#include "google/protobuf/generated_message_tctable_impl.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::google::protobuf;
namespace _pbi = ::google::protobuf::internal;
namespace _fl = ::google::protobuf::internal::field_layout;
namespace nvidia_ace {
namespace services {
namespace a2x_export_config {
namespace v1 {

inline constexpr ConfigsTypeRequest::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : config_type_{static_cast< ::nvidia_ace::services::a2x_export_config::v1::ConfigsTypeRequest_ConfigType >(0)},
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR ConfigsTypeRequest::ConfigsTypeRequest(::_pbi::ConstantInitialized)
    : _impl_(::_pbi::ConstantInitialized()) {}
struct ConfigsTypeRequestDefaultTypeInternal {
  PROTOBUF_CONSTEXPR ConfigsTypeRequestDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~ConfigsTypeRequestDefaultTypeInternal() {}
  union {
    ConfigsTypeRequest _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 ConfigsTypeRequestDefaultTypeInternal _ConfigsTypeRequest_default_instance_;

inline constexpr A2XConfig::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : name_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        content_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR A2XConfig::A2XConfig(::_pbi::ConstantInitialized)
    : _impl_(::_pbi::ConstantInitialized()) {}
struct A2XConfigDefaultTypeInternal {
  PROTOBUF_CONSTEXPR A2XConfigDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~A2XConfigDefaultTypeInternal() {}
  union {
    A2XConfig _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 A2XConfigDefaultTypeInternal _A2XConfig_default_instance_;
}  // namespace v1
}  // namespace a2x_export_config
}  // namespace services
}  // namespace nvidia_ace
static ::_pb::Metadata file_level_metadata_nvidia_5face_2eservices_2ea2x_5fexport_5fconfig_2ev1_2eproto[2];
static const ::_pb::EnumDescriptor* file_level_enum_descriptors_nvidia_5face_2eservices_2ea2x_5fexport_5fconfig_2ev1_2eproto[1];
static constexpr const ::_pb::ServiceDescriptor**
    file_level_service_descriptors_nvidia_5face_2eservices_2ea2x_5fexport_5fconfig_2ev1_2eproto = nullptr;
const ::uint32_t
    TableStruct_nvidia_5face_2eservices_2ea2x_5fexport_5fconfig_2ev1_2eproto::offsets[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
        protodesc_cold) = {
        ~0u,  // no _has_bits_
        PROTOBUF_FIELD_OFFSET(::nvidia_ace::services::a2x_export_config::v1::ConfigsTypeRequest, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::nvidia_ace::services::a2x_export_config::v1::ConfigsTypeRequest, _impl_.config_type_),
        ~0u,  // no _has_bits_
        PROTOBUF_FIELD_OFFSET(::nvidia_ace::services::a2x_export_config::v1::A2XConfig, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::nvidia_ace::services::a2x_export_config::v1::A2XConfig, _impl_.name_),
        PROTOBUF_FIELD_OFFSET(::nvidia_ace::services::a2x_export_config::v1::A2XConfig, _impl_.content_),
};

static const ::_pbi::MigrationSchema
    schemas[] ABSL_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
        {0, -1, -1, sizeof(::nvidia_ace::services::a2x_export_config::v1::ConfigsTypeRequest)},
        {9, -1, -1, sizeof(::nvidia_ace::services::a2x_export_config::v1::A2XConfig)},
};
static const ::_pb::Message* const file_default_instances[] = {
    &::nvidia_ace::services::a2x_export_config::v1::_ConfigsTypeRequest_default_instance_._instance,
    &::nvidia_ace::services::a2x_export_config::v1::_A2XConfig_default_instance_._instance,
};
const char descriptor_table_protodef_nvidia_5face_2eservices_2ea2x_5fexport_5fconfig_2ev1_2eproto[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
    protodesc_cold) = {
    "\n.nvidia_ace.services.a2x_export_config."
    "v1.proto\022(nvidia_ace.services.a2x_export"
    "_config.v1\"\224\001\n\022ConfigsTypeRequest\022\\\n\013con"
    "fig_type\030\001 \001(\0162G.nvidia_ace.services.a2x"
    "_export_config.v1.ConfigsTypeRequest.Con"
    "figType\" \n\nConfigType\022\010\n\004YAML\020\000\022\010\n\004JSON\020"
    "\001\"*\n\tA2XConfig\022\014\n\004name\030\001 \001(\t\022\017\n\007content\030"
    "\002 \001(\t2\236\001\n\026A2XExportConfigService\022\203\001\n\nGet"
    "Configs\022<.nvidia_ace.services.a2x_export"
    "_config.v1.ConfigsTypeRequest\0323.nvidia_a"
    "ce.services.a2x_export_config.v1.A2XConf"
    "ig\"\0000\001b\006proto3"
};
static ::absl::once_flag descriptor_table_nvidia_5face_2eservices_2ea2x_5fexport_5fconfig_2ev1_2eproto_once;
const ::_pbi::DescriptorTable descriptor_table_nvidia_5face_2eservices_2ea2x_5fexport_5fconfig_2ev1_2eproto = {
    false,
    false,
    454,
    descriptor_table_protodef_nvidia_5face_2eservices_2ea2x_5fexport_5fconfig_2ev1_2eproto,
    "nvidia_ace.services.a2x_export_config.v1.proto",
    &descriptor_table_nvidia_5face_2eservices_2ea2x_5fexport_5fconfig_2ev1_2eproto_once,
    nullptr,
    0,
    2,
    schemas,
    file_default_instances,
    TableStruct_nvidia_5face_2eservices_2ea2x_5fexport_5fconfig_2ev1_2eproto::offsets,
    file_level_metadata_nvidia_5face_2eservices_2ea2x_5fexport_5fconfig_2ev1_2eproto,
    file_level_enum_descriptors_nvidia_5face_2eservices_2ea2x_5fexport_5fconfig_2ev1_2eproto,
    file_level_service_descriptors_nvidia_5face_2eservices_2ea2x_5fexport_5fconfig_2ev1_2eproto,
};

// This function exists to be marked as weak.
// It can significantly speed up compilation by breaking up LLVM's SCC
// in the .pb.cc translation units. Large translation units see a
// reduction of more than 35% of walltime for optimized builds. Without
// the weak attribute all the messages in the file, including all the
// vtables and everything they use become part of the same SCC through
// a cycle like:
// GetMetadata -> descriptor table -> default instances ->
//   vtables -> GetMetadata
// By adding a weak function here we break the connection from the
// individual vtables back into the descriptor table.
PROTOBUF_ATTRIBUTE_WEAK const ::_pbi::DescriptorTable* descriptor_table_nvidia_5face_2eservices_2ea2x_5fexport_5fconfig_2ev1_2eproto_getter() {
  return &descriptor_table_nvidia_5face_2eservices_2ea2x_5fexport_5fconfig_2ev1_2eproto;
}
namespace nvidia_ace {
namespace services {
namespace a2x_export_config {
namespace v1 {
const ::google::protobuf::EnumDescriptor* ConfigsTypeRequest_ConfigType_descriptor() {
  ::google::protobuf::internal::AssignDescriptors(&descriptor_table_nvidia_5face_2eservices_2ea2x_5fexport_5fconfig_2ev1_2eproto);
  return file_level_enum_descriptors_nvidia_5face_2eservices_2ea2x_5fexport_5fconfig_2ev1_2eproto[0];
}
PROTOBUF_CONSTINIT const uint32_t ConfigsTypeRequest_ConfigType_internal_data_[] = {
    131072u, 0u, };
bool ConfigsTypeRequest_ConfigType_IsValid(int value) {
  return 0 <= value && value <= 1;
}
#if (__cplusplus < 201703) && \
  (!defined(_MSC_VER) || (_MSC_VER >= 1900 && _MSC_VER < 1912))

constexpr ConfigsTypeRequest_ConfigType ConfigsTypeRequest::YAML;
constexpr ConfigsTypeRequest_ConfigType ConfigsTypeRequest::JSON;
constexpr ConfigsTypeRequest_ConfigType ConfigsTypeRequest::ConfigType_MIN;
constexpr ConfigsTypeRequest_ConfigType ConfigsTypeRequest::ConfigType_MAX;
constexpr int ConfigsTypeRequest::ConfigType_ARRAYSIZE;

#endif  // (__cplusplus < 201703) &&
        // (!defined(_MSC_VER) || (_MSC_VER >= 1900 && _MSC_VER < 1912))
// ===================================================================

class ConfigsTypeRequest::_Internal {
 public:
};

ConfigsTypeRequest::ConfigsTypeRequest(::google::protobuf::Arena* arena)
    : ::google::protobuf::Message(arena) {
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:nvidia_ace.services.a2x_export_config.v1.ConfigsTypeRequest)
}
ConfigsTypeRequest::ConfigsTypeRequest(
    ::google::protobuf::Arena* arena, const ConfigsTypeRequest& from)
    : ConfigsTypeRequest(arena) {
  MergeFrom(from);
}
inline PROTOBUF_NDEBUG_INLINE ConfigsTypeRequest::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : _cached_size_{0} {}

inline void ConfigsTypeRequest::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  _impl_.config_type_ = {};
}
ConfigsTypeRequest::~ConfigsTypeRequest() {
  // @@protoc_insertion_point(destructor:nvidia_ace.services.a2x_export_config.v1.ConfigsTypeRequest)
  _internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  SharedDtor();
}
inline void ConfigsTypeRequest::SharedDtor() {
  ABSL_DCHECK(GetArena() == nullptr);
  _impl_.~Impl_();
}

const ::google::protobuf::MessageLite::ClassData*
ConfigsTypeRequest::GetClassData() const {
  PROTOBUF_CONSTINIT static const ::google::protobuf::MessageLite::
      ClassDataFull _data_ = {
          {
              nullptr,  // OnDemandRegisterArenaDtor
              PROTOBUF_FIELD_OFFSET(ConfigsTypeRequest, _impl_._cached_size_),
              false,
          },
          &ConfigsTypeRequest::MergeImpl,
          &ConfigsTypeRequest::kDescriptorMethods,
      };
  return &_data_;
}
PROTOBUF_NOINLINE void ConfigsTypeRequest::Clear() {
// @@protoc_insertion_point(message_clear_start:nvidia_ace.services.a2x_export_config.v1.ConfigsTypeRequest)
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.config_type_ = 0;
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

const char* ConfigsTypeRequest::_InternalParse(
    const char* ptr, ::_pbi::ParseContext* ctx) {
  ptr = ::_pbi::TcParser::ParseLoop(this, ptr, ctx, &_table_.header);
  return ptr;
}


PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<0, 1, 0, 0, 2> ConfigsTypeRequest::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    1, 0,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967294,  // skipmap
    offsetof(decltype(_table_), field_entries),
    1,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    &_ConfigsTypeRequest_default_instance_._instance,
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::nvidia_ace::services::a2x_export_config::v1::ConfigsTypeRequest>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // .nvidia_ace.services.a2x_export_config.v1.ConfigsTypeRequest.ConfigType config_type = 1;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(ConfigsTypeRequest, _impl_.config_type_), 63>(),
     {8, 63, 0, PROTOBUF_FIELD_OFFSET(ConfigsTypeRequest, _impl_.config_type_)}},
  }}, {{
    65535, 65535
  }}, {{
    // .nvidia_ace.services.a2x_export_config.v1.ConfigsTypeRequest.ConfigType config_type = 1;
    {PROTOBUF_FIELD_OFFSET(ConfigsTypeRequest, _impl_.config_type_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kOpenEnum)},
  }},
  // no aux_entries
  {{
  }},
};

::uint8_t* ConfigsTypeRequest::_InternalSerialize(
    ::uint8_t* target,
    ::google::protobuf::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:nvidia_ace.services.a2x_export_config.v1.ConfigsTypeRequest)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  // .nvidia_ace.services.a2x_export_config.v1.ConfigsTypeRequest.ConfigType config_type = 1;
  if (this->_internal_config_type() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteEnumToArray(
        1, this->_internal_config_type(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:nvidia_ace.services.a2x_export_config.v1.ConfigsTypeRequest)
  return target;
}

::size_t ConfigsTypeRequest::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:nvidia_ace.services.a2x_export_config.v1.ConfigsTypeRequest)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // .nvidia_ace.services.a2x_export_config.v1.ConfigsTypeRequest.ConfigType config_type = 1;
  if (this->_internal_config_type() != 0) {
    total_size += 1 +
                  ::_pbi::WireFormatLite::EnumSize(this->_internal_config_type());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}


void ConfigsTypeRequest::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<ConfigsTypeRequest*>(&to_msg);
  auto& from = static_cast<const ConfigsTypeRequest&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:nvidia_ace.services.a2x_export_config.v1.ConfigsTypeRequest)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (from._internal_config_type() != 0) {
    _this->_impl_.config_type_ = from._impl_.config_type_;
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void ConfigsTypeRequest::CopyFrom(const ConfigsTypeRequest& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:nvidia_ace.services.a2x_export_config.v1.ConfigsTypeRequest)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

PROTOBUF_NOINLINE bool ConfigsTypeRequest::IsInitialized() const {
  return true;
}

void ConfigsTypeRequest::InternalSwap(ConfigsTypeRequest* PROTOBUF_RESTRICT other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_.config_type_, other->_impl_.config_type_);
}

::google::protobuf::Metadata ConfigsTypeRequest::GetMetadata() const {
  return ::_pbi::AssignDescriptors(&descriptor_table_nvidia_5face_2eservices_2ea2x_5fexport_5fconfig_2ev1_2eproto_getter,
                                   &descriptor_table_nvidia_5face_2eservices_2ea2x_5fexport_5fconfig_2ev1_2eproto_once,
                                   file_level_metadata_nvidia_5face_2eservices_2ea2x_5fexport_5fconfig_2ev1_2eproto[0]);
}
// ===================================================================

class A2XConfig::_Internal {
 public:
};

A2XConfig::A2XConfig(::google::protobuf::Arena* arena)
    : ::google::protobuf::Message(arena) {
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:nvidia_ace.services.a2x_export_config.v1.A2XConfig)
}
inline PROTOBUF_NDEBUG_INLINE A2XConfig::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from)
      : name_(arena, from.name_),
        content_(arena, from.content_),
        _cached_size_{0} {}

A2XConfig::A2XConfig(
    ::google::protobuf::Arena* arena,
    const A2XConfig& from)
    : ::google::protobuf::Message(arena) {
  A2XConfig* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_);

  // @@protoc_insertion_point(copy_constructor:nvidia_ace.services.a2x_export_config.v1.A2XConfig)
}
inline PROTOBUF_NDEBUG_INLINE A2XConfig::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : name_(arena),
        content_(arena),
        _cached_size_{0} {}

inline void A2XConfig::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
}
A2XConfig::~A2XConfig() {
  // @@protoc_insertion_point(destructor:nvidia_ace.services.a2x_export_config.v1.A2XConfig)
  _internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  SharedDtor();
}
inline void A2XConfig::SharedDtor() {
  ABSL_DCHECK(GetArena() == nullptr);
  _impl_.name_.Destroy();
  _impl_.content_.Destroy();
  _impl_.~Impl_();
}

const ::google::protobuf::MessageLite::ClassData*
A2XConfig::GetClassData() const {
  PROTOBUF_CONSTINIT static const ::google::protobuf::MessageLite::
      ClassDataFull _data_ = {
          {
              nullptr,  // OnDemandRegisterArenaDtor
              PROTOBUF_FIELD_OFFSET(A2XConfig, _impl_._cached_size_),
              false,
          },
          &A2XConfig::MergeImpl,
          &A2XConfig::kDescriptorMethods,
      };
  return &_data_;
}
PROTOBUF_NOINLINE void A2XConfig::Clear() {
// @@protoc_insertion_point(message_clear_start:nvidia_ace.services.a2x_export_config.v1.A2XConfig)
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.name_.ClearToEmpty();
  _impl_.content_.ClearToEmpty();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

const char* A2XConfig::_InternalParse(
    const char* ptr, ::_pbi::ParseContext* ctx) {
  ptr = ::_pbi::TcParser::ParseLoop(this, ptr, ctx, &_table_.header);
  return ptr;
}


PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<1, 2, 0, 70, 2> A2XConfig::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    2, 8,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967292,  // skipmap
    offsetof(decltype(_table_), field_entries),
    2,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    &_A2XConfig_default_instance_._instance,
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::nvidia_ace::services::a2x_export_config::v1::A2XConfig>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // string content = 2;
    {::_pbi::TcParser::FastUS1,
     {18, 63, 0, PROTOBUF_FIELD_OFFSET(A2XConfig, _impl_.content_)}},
    // string name = 1;
    {::_pbi::TcParser::FastUS1,
     {10, 63, 0, PROTOBUF_FIELD_OFFSET(A2XConfig, _impl_.name_)}},
  }}, {{
    65535, 65535
  }}, {{
    // string name = 1;
    {PROTOBUF_FIELD_OFFSET(A2XConfig, _impl_.name_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
    // string content = 2;
    {PROTOBUF_FIELD_OFFSET(A2XConfig, _impl_.content_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
  }},
  // no aux_entries
  {{
    "\62\4\7\0\0\0\0\0"
    "nvidia_ace.services.a2x_export_config.v1.A2XConfig"
    "name"
    "content"
  }},
};

::uint8_t* A2XConfig::_InternalSerialize(
    ::uint8_t* target,
    ::google::protobuf::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:nvidia_ace.services.a2x_export_config.v1.A2XConfig)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  // string name = 1;
  if (!this->_internal_name().empty()) {
    const std::string& _s = this->_internal_name();
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
        _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "nvidia_ace.services.a2x_export_config.v1.A2XConfig.name");
    target = stream->WriteStringMaybeAliased(1, _s, target);
  }

  // string content = 2;
  if (!this->_internal_content().empty()) {
    const std::string& _s = this->_internal_content();
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
        _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "nvidia_ace.services.a2x_export_config.v1.A2XConfig.content");
    target = stream->WriteStringMaybeAliased(2, _s, target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:nvidia_ace.services.a2x_export_config.v1.A2XConfig)
  return target;
}

::size_t A2XConfig::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:nvidia_ace.services.a2x_export_config.v1.A2XConfig)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // string name = 1;
  if (!this->_internal_name().empty()) {
    total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                    this->_internal_name());
  }

  // string content = 2;
  if (!this->_internal_content().empty()) {
    total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                    this->_internal_content());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}


void A2XConfig::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<A2XConfig*>(&to_msg);
  auto& from = static_cast<const A2XConfig&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:nvidia_ace.services.a2x_export_config.v1.A2XConfig)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_name().empty()) {
    _this->_internal_set_name(from._internal_name());
  }
  if (!from._internal_content().empty()) {
    _this->_internal_set_content(from._internal_content());
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void A2XConfig::CopyFrom(const A2XConfig& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:nvidia_ace.services.a2x_export_config.v1.A2XConfig)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

PROTOBUF_NOINLINE bool A2XConfig::IsInitialized() const {
  return true;
}

void A2XConfig::InternalSwap(A2XConfig* PROTOBUF_RESTRICT other) {
  using std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.name_, &other->_impl_.name_, arena);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.content_, &other->_impl_.content_, arena);
}

::google::protobuf::Metadata A2XConfig::GetMetadata() const {
  return ::_pbi::AssignDescriptors(&descriptor_table_nvidia_5face_2eservices_2ea2x_5fexport_5fconfig_2ev1_2eproto_getter,
                                   &descriptor_table_nvidia_5face_2eservices_2ea2x_5fexport_5fconfig_2ev1_2eproto_once,
                                   file_level_metadata_nvidia_5face_2eservices_2ea2x_5fexport_5fconfig_2ev1_2eproto[1]);
}
// @@protoc_insertion_point(namespace_scope)
}  // namespace v1
}  // namespace a2x_export_config
}  // namespace services
}  // namespace nvidia_ace
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google
// @@protoc_insertion_point(global_scope)
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2
static ::std::false_type _static_init_ PROTOBUF_UNUSED =
    (::_pbi::AddDescriptors(&descriptor_table_nvidia_5face_2eservices_2ea2x_5fexport_5fconfig_2ev1_2eproto),
     ::std::false_type{});
#include "google/protobuf/port_undef.inc"
