// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: nvidia_ace.services.a2x_export_config.v1.proto
#ifndef GRPC_nvidia_5face_2eservices_2ea2x_5fexport_5fconfig_2ev1_2eproto__INCLUDED
#define GRPC_nvidia_5face_2eservices_2ea2x_5fexport_5fconfig_2ev1_2eproto__INCLUDED

#include "nvidia_ace.services.a2x_export_config.v1.pb.h"

#include <functional>
#include <grpcpp/generic/async_generic_service.h>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/client_context.h>
#include <grpcpp/completion_queue.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/proto_utils.h>
#include <grpcpp/impl/rpc_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/support/status.h>
#include <grpcpp/support/stub_options.h>
#include <grpcpp/support/sync_stream.h>

namespace nvidia_ace {
namespace services {
namespace a2x_export_config {
namespace v1 {

class A2XExportConfigService final {
 public:
  static constexpr char const* service_full_name() {
    return "nvidia_ace.services.a2x_export_config.v1.A2XExportConfigService";
  }
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    std::unique_ptr< ::grpc::ClientReaderInterface< ::nvidia_ace::services::a2x_export_config::v1::A2XConfig>> GetConfigs(::grpc::ClientContext* context, const ::nvidia_ace::services::a2x_export_config::v1::ConfigsTypeRequest& request) {
      return std::unique_ptr< ::grpc::ClientReaderInterface< ::nvidia_ace::services::a2x_export_config::v1::A2XConfig>>(GetConfigsRaw(context, request));
    }
    std::unique_ptr< ::grpc::ClientAsyncReaderInterface< ::nvidia_ace::services::a2x_export_config::v1::A2XConfig>> AsyncGetConfigs(::grpc::ClientContext* context, const ::nvidia_ace::services::a2x_export_config::v1::ConfigsTypeRequest& request, ::grpc::CompletionQueue* cq, void* tag) {
      return std::unique_ptr< ::grpc::ClientAsyncReaderInterface< ::nvidia_ace::services::a2x_export_config::v1::A2XConfig>>(AsyncGetConfigsRaw(context, request, cq, tag));
    }
    std::unique_ptr< ::grpc::ClientAsyncReaderInterface< ::nvidia_ace::services::a2x_export_config::v1::A2XConfig>> PrepareAsyncGetConfigs(::grpc::ClientContext* context, const ::nvidia_ace::services::a2x_export_config::v1::ConfigsTypeRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncReaderInterface< ::nvidia_ace::services::a2x_export_config::v1::A2XConfig>>(PrepareAsyncGetConfigsRaw(context, request, cq));
    }
    class async_interface {
     public:
      virtual ~async_interface() {}
      virtual void GetConfigs(::grpc::ClientContext* context, const ::nvidia_ace::services::a2x_export_config::v1::ConfigsTypeRequest* request, ::grpc::ClientReadReactor< ::nvidia_ace::services::a2x_export_config::v1::A2XConfig>* reactor) = 0;
    };
    typedef class async_interface experimental_async_interface;
    virtual class async_interface* async() { return nullptr; }
    class async_interface* experimental_async() { return async(); }
   private:
    virtual ::grpc::ClientReaderInterface< ::nvidia_ace::services::a2x_export_config::v1::A2XConfig>* GetConfigsRaw(::grpc::ClientContext* context, const ::nvidia_ace::services::a2x_export_config::v1::ConfigsTypeRequest& request) = 0;
    virtual ::grpc::ClientAsyncReaderInterface< ::nvidia_ace::services::a2x_export_config::v1::A2XConfig>* AsyncGetConfigsRaw(::grpc::ClientContext* context, const ::nvidia_ace::services::a2x_export_config::v1::ConfigsTypeRequest& request, ::grpc::CompletionQueue* cq, void* tag) = 0;
    virtual ::grpc::ClientAsyncReaderInterface< ::nvidia_ace::services::a2x_export_config::v1::A2XConfig>* PrepareAsyncGetConfigsRaw(::grpc::ClientContext* context, const ::nvidia_ace::services::a2x_export_config::v1::ConfigsTypeRequest& request, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());
    std::unique_ptr< ::grpc::ClientReader< ::nvidia_ace::services::a2x_export_config::v1::A2XConfig>> GetConfigs(::grpc::ClientContext* context, const ::nvidia_ace::services::a2x_export_config::v1::ConfigsTypeRequest& request) {
      return std::unique_ptr< ::grpc::ClientReader< ::nvidia_ace::services::a2x_export_config::v1::A2XConfig>>(GetConfigsRaw(context, request));
    }
    std::unique_ptr< ::grpc::ClientAsyncReader< ::nvidia_ace::services::a2x_export_config::v1::A2XConfig>> AsyncGetConfigs(::grpc::ClientContext* context, const ::nvidia_ace::services::a2x_export_config::v1::ConfigsTypeRequest& request, ::grpc::CompletionQueue* cq, void* tag) {
      return std::unique_ptr< ::grpc::ClientAsyncReader< ::nvidia_ace::services::a2x_export_config::v1::A2XConfig>>(AsyncGetConfigsRaw(context, request, cq, tag));
    }
    std::unique_ptr< ::grpc::ClientAsyncReader< ::nvidia_ace::services::a2x_export_config::v1::A2XConfig>> PrepareAsyncGetConfigs(::grpc::ClientContext* context, const ::nvidia_ace::services::a2x_export_config::v1::ConfigsTypeRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncReader< ::nvidia_ace::services::a2x_export_config::v1::A2XConfig>>(PrepareAsyncGetConfigsRaw(context, request, cq));
    }
    class async final :
      public StubInterface::async_interface {
     public:
      void GetConfigs(::grpc::ClientContext* context, const ::nvidia_ace::services::a2x_export_config::v1::ConfigsTypeRequest* request, ::grpc::ClientReadReactor< ::nvidia_ace::services::a2x_export_config::v1::A2XConfig>* reactor) override;
     private:
      friend class Stub;
      explicit async(Stub* stub): stub_(stub) { }
      Stub* stub() { return stub_; }
      Stub* stub_;
    };
    class async* async() override { return &async_stub_; }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    class async async_stub_{this};
    ::grpc::ClientReader< ::nvidia_ace::services::a2x_export_config::v1::A2XConfig>* GetConfigsRaw(::grpc::ClientContext* context, const ::nvidia_ace::services::a2x_export_config::v1::ConfigsTypeRequest& request) override;
    ::grpc::ClientAsyncReader< ::nvidia_ace::services::a2x_export_config::v1::A2XConfig>* AsyncGetConfigsRaw(::grpc::ClientContext* context, const ::nvidia_ace::services::a2x_export_config::v1::ConfigsTypeRequest& request, ::grpc::CompletionQueue* cq, void* tag) override;
    ::grpc::ClientAsyncReader< ::nvidia_ace::services::a2x_export_config::v1::A2XConfig>* PrepareAsyncGetConfigsRaw(::grpc::ClientContext* context, const ::nvidia_ace::services::a2x_export_config::v1::ConfigsTypeRequest& request, ::grpc::CompletionQueue* cq) override;
    const ::grpc::internal::RpcMethod rpcmethod_GetConfigs_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    virtual ::grpc::Status GetConfigs(::grpc::ServerContext* context, const ::nvidia_ace::services::a2x_export_config::v1::ConfigsTypeRequest* request, ::grpc::ServerWriter< ::nvidia_ace::services::a2x_export_config::v1::A2XConfig>* writer);
  };
  template <class BaseClass>
  class WithAsyncMethod_GetConfigs : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_GetConfigs() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_GetConfigs() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetConfigs(::grpc::ServerContext* /*context*/, const ::nvidia_ace::services::a2x_export_config::v1::ConfigsTypeRequest* /*request*/, ::grpc::ServerWriter< ::nvidia_ace::services::a2x_export_config::v1::A2XConfig>* /*writer*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestGetConfigs(::grpc::ServerContext* context, ::nvidia_ace::services::a2x_export_config::v1::ConfigsTypeRequest* request, ::grpc::ServerAsyncWriter< ::nvidia_ace::services::a2x_export_config::v1::A2XConfig>* writer, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncServerStreaming(0, context, request, writer, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_GetConfigs<Service > AsyncService;
  template <class BaseClass>
  class WithCallbackMethod_GetConfigs : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_GetConfigs() {
      ::grpc::Service::MarkMethodCallback(0,
          new ::grpc::internal::CallbackServerStreamingHandler< ::nvidia_ace::services::a2x_export_config::v1::ConfigsTypeRequest, ::nvidia_ace::services::a2x_export_config::v1::A2XConfig>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::nvidia_ace::services::a2x_export_config::v1::ConfigsTypeRequest* request) { return this->GetConfigs(context, request); }));
    }
    ~WithCallbackMethod_GetConfigs() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetConfigs(::grpc::ServerContext* /*context*/, const ::nvidia_ace::services::a2x_export_config::v1::ConfigsTypeRequest* /*request*/, ::grpc::ServerWriter< ::nvidia_ace::services::a2x_export_config::v1::A2XConfig>* /*writer*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerWriteReactor< ::nvidia_ace::services::a2x_export_config::v1::A2XConfig>* GetConfigs(
      ::grpc::CallbackServerContext* /*context*/, const ::nvidia_ace::services::a2x_export_config::v1::ConfigsTypeRequest* /*request*/)  { return nullptr; }
  };
  typedef WithCallbackMethod_GetConfigs<Service > CallbackService;
  typedef CallbackService ExperimentalCallbackService;
  template <class BaseClass>
  class WithGenericMethod_GetConfigs : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_GetConfigs() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_GetConfigs() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetConfigs(::grpc::ServerContext* /*context*/, const ::nvidia_ace::services::a2x_export_config::v1::ConfigsTypeRequest* /*request*/, ::grpc::ServerWriter< ::nvidia_ace::services::a2x_export_config::v1::A2XConfig>* /*writer*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithRawMethod_GetConfigs : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_GetConfigs() {
      ::grpc::Service::MarkMethodRaw(0);
    }
    ~WithRawMethod_GetConfigs() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetConfigs(::grpc::ServerContext* /*context*/, const ::nvidia_ace::services::a2x_export_config::v1::ConfigsTypeRequest* /*request*/, ::grpc::ServerWriter< ::nvidia_ace::services::a2x_export_config::v1::A2XConfig>* /*writer*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestGetConfigs(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncWriter< ::grpc::ByteBuffer>* writer, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncServerStreaming(0, context, request, writer, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_GetConfigs : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_GetConfigs() {
      ::grpc::Service::MarkMethodRawCallback(0,
          new ::grpc::internal::CallbackServerStreamingHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const::grpc::ByteBuffer* request) { return this->GetConfigs(context, request); }));
    }
    ~WithRawCallbackMethod_GetConfigs() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetConfigs(::grpc::ServerContext* /*context*/, const ::nvidia_ace::services::a2x_export_config::v1::ConfigsTypeRequest* /*request*/, ::grpc::ServerWriter< ::nvidia_ace::services::a2x_export_config::v1::A2XConfig>* /*writer*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerWriteReactor< ::grpc::ByteBuffer>* GetConfigs(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/)  { return nullptr; }
  };
  typedef Service StreamedUnaryService;
  template <class BaseClass>
  class WithSplitStreamingMethod_GetConfigs : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithSplitStreamingMethod_GetConfigs() {
      ::grpc::Service::MarkMethodStreamed(0,
        new ::grpc::internal::SplitServerStreamingHandler<
          ::nvidia_ace::services::a2x_export_config::v1::ConfigsTypeRequest, ::nvidia_ace::services::a2x_export_config::v1::A2XConfig>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerSplitStreamer<
                     ::nvidia_ace::services::a2x_export_config::v1::ConfigsTypeRequest, ::nvidia_ace::services::a2x_export_config::v1::A2XConfig>* streamer) {
                       return this->StreamedGetConfigs(context,
                         streamer);
                  }));
    }
    ~WithSplitStreamingMethod_GetConfigs() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status GetConfigs(::grpc::ServerContext* /*context*/, const ::nvidia_ace::services::a2x_export_config::v1::ConfigsTypeRequest* /*request*/, ::grpc::ServerWriter< ::nvidia_ace::services::a2x_export_config::v1::A2XConfig>* /*writer*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with split streamed
    virtual ::grpc::Status StreamedGetConfigs(::grpc::ServerContext* context, ::grpc::ServerSplitStreamer< ::nvidia_ace::services::a2x_export_config::v1::ConfigsTypeRequest,::nvidia_ace::services::a2x_export_config::v1::A2XConfig>* server_split_streamer) = 0;
  };
  typedef WithSplitStreamingMethod_GetConfigs<Service > SplitStreamedService;
  typedef WithSplitStreamingMethod_GetConfigs<Service > StreamedService;
};

}  // namespace v1
}  // namespace a2x_export_config
}  // namespace services
}  // namespace nvidia_ace


#endif  // GRPC_nvidia_5face_2eservices_2ea2x_5fexport_5fconfig_2ev1_2eproto__INCLUDED
