// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: nvidia_ace.services.a2f_authoring.v1.proto
// Original file comments:
// Copyright (c) 2024 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
//
#ifndef GRPC_nvidia_5face_2eservices_2ea2f_5fauthoring_2ev1_2eproto__INCLUDED
#define GRPC_nvidia_5face_2eservices_2ea2f_5fauthoring_2ev1_2eproto__INCLUDED

#include "nvidia_ace.services.a2f_authoring.v1.pb.h"

#include <functional>
#include <grpcpp/generic/async_generic_service.h>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/client_context.h>
#include <grpcpp/completion_queue.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/proto_utils.h>
#include <grpcpp/impl/rpc_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/support/status.h>
#include <grpcpp/support/stub_options.h>
#include <grpcpp/support/sync_stream.h>

namespace nvidia_ace {
namespace services {
namespace a2f_authoring {
namespace v1 {

// This API allows to get unique frames from Audio2Face inference (also known as authoring)
class A2FAuthoringService final {
 public:
  static constexpr char const* service_full_name() {
    return "nvidia_ace.services.a2f_authoring.v1.A2FAuthoringService";
  }
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    // Upload the audio clip to the AuthoringService to be processed.
    virtual ::grpc::Status UploadAudioClip(::grpc::ClientContext* context, const ::nvidia_ace::a2f_authoring::v1::AudioClip& request, ::nvidia_ace::a2f_authoring::v1::AudioClipHandle* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::nvidia_ace::a2f_authoring::v1::AudioClipHandle>> AsyncUploadAudioClip(::grpc::ClientContext* context, const ::nvidia_ace::a2f_authoring::v1::AudioClip& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::nvidia_ace::a2f_authoring::v1::AudioClipHandle>>(AsyncUploadAudioClipRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::nvidia_ace::a2f_authoring::v1::AudioClipHandle>> PrepareAsyncUploadAudioClip(::grpc::ClientContext* context, const ::nvidia_ace::a2f_authoring::v1::AudioClip& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::nvidia_ace::a2f_authoring::v1::AudioClipHandle>>(PrepareAsyncUploadAudioClipRaw(context, request, cq));
    }
    // Request a single animation frame at the specified timecode.
    virtual ::grpc::Status GetAvatarFacePose(::grpc::ClientContext* context, const ::nvidia_ace::a2f_authoring::v1::FacePoseRequest& request, ::nvidia_ace::a2f_authoring::v1::BlendShapeData* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::nvidia_ace::a2f_authoring::v1::BlendShapeData>> AsyncGetAvatarFacePose(::grpc::ClientContext* context, const ::nvidia_ace::a2f_authoring::v1::FacePoseRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::nvidia_ace::a2f_authoring::v1::BlendShapeData>>(AsyncGetAvatarFacePoseRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::nvidia_ace::a2f_authoring::v1::BlendShapeData>> PrepareAsyncGetAvatarFacePose(::grpc::ClientContext* context, const ::nvidia_ace::a2f_authoring::v1::FacePoseRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::nvidia_ace::a2f_authoring::v1::BlendShapeData>>(PrepareAsyncGetAvatarFacePoseRaw(context, request, cq));
    }
    class async_interface {
     public:
      virtual ~async_interface() {}
      // Upload the audio clip to the AuthoringService to be processed.
      virtual void UploadAudioClip(::grpc::ClientContext* context, const ::nvidia_ace::a2f_authoring::v1::AudioClip* request, ::nvidia_ace::a2f_authoring::v1::AudioClipHandle* response, std::function<void(::grpc::Status)>) = 0;
      virtual void UploadAudioClip(::grpc::ClientContext* context, const ::nvidia_ace::a2f_authoring::v1::AudioClip* request, ::nvidia_ace::a2f_authoring::v1::AudioClipHandle* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      // Request a single animation frame at the specified timecode.
      virtual void GetAvatarFacePose(::grpc::ClientContext* context, const ::nvidia_ace::a2f_authoring::v1::FacePoseRequest* request, ::nvidia_ace::a2f_authoring::v1::BlendShapeData* response, std::function<void(::grpc::Status)>) = 0;
      virtual void GetAvatarFacePose(::grpc::ClientContext* context, const ::nvidia_ace::a2f_authoring::v1::FacePoseRequest* request, ::nvidia_ace::a2f_authoring::v1::BlendShapeData* response, ::grpc::ClientUnaryReactor* reactor) = 0;
    };
    typedef class async_interface experimental_async_interface;
    virtual class async_interface* async() { return nullptr; }
    class async_interface* experimental_async() { return async(); }
   private:
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::nvidia_ace::a2f_authoring::v1::AudioClipHandle>* AsyncUploadAudioClipRaw(::grpc::ClientContext* context, const ::nvidia_ace::a2f_authoring::v1::AudioClip& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::nvidia_ace::a2f_authoring::v1::AudioClipHandle>* PrepareAsyncUploadAudioClipRaw(::grpc::ClientContext* context, const ::nvidia_ace::a2f_authoring::v1::AudioClip& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::nvidia_ace::a2f_authoring::v1::BlendShapeData>* AsyncGetAvatarFacePoseRaw(::grpc::ClientContext* context, const ::nvidia_ace::a2f_authoring::v1::FacePoseRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::nvidia_ace::a2f_authoring::v1::BlendShapeData>* PrepareAsyncGetAvatarFacePoseRaw(::grpc::ClientContext* context, const ::nvidia_ace::a2f_authoring::v1::FacePoseRequest& request, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());
    ::grpc::Status UploadAudioClip(::grpc::ClientContext* context, const ::nvidia_ace::a2f_authoring::v1::AudioClip& request, ::nvidia_ace::a2f_authoring::v1::AudioClipHandle* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::nvidia_ace::a2f_authoring::v1::AudioClipHandle>> AsyncUploadAudioClip(::grpc::ClientContext* context, const ::nvidia_ace::a2f_authoring::v1::AudioClip& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::nvidia_ace::a2f_authoring::v1::AudioClipHandle>>(AsyncUploadAudioClipRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::nvidia_ace::a2f_authoring::v1::AudioClipHandle>> PrepareAsyncUploadAudioClip(::grpc::ClientContext* context, const ::nvidia_ace::a2f_authoring::v1::AudioClip& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::nvidia_ace::a2f_authoring::v1::AudioClipHandle>>(PrepareAsyncUploadAudioClipRaw(context, request, cq));
    }
    ::grpc::Status GetAvatarFacePose(::grpc::ClientContext* context, const ::nvidia_ace::a2f_authoring::v1::FacePoseRequest& request, ::nvidia_ace::a2f_authoring::v1::BlendShapeData* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::nvidia_ace::a2f_authoring::v1::BlendShapeData>> AsyncGetAvatarFacePose(::grpc::ClientContext* context, const ::nvidia_ace::a2f_authoring::v1::FacePoseRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::nvidia_ace::a2f_authoring::v1::BlendShapeData>>(AsyncGetAvatarFacePoseRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::nvidia_ace::a2f_authoring::v1::BlendShapeData>> PrepareAsyncGetAvatarFacePose(::grpc::ClientContext* context, const ::nvidia_ace::a2f_authoring::v1::FacePoseRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::nvidia_ace::a2f_authoring::v1::BlendShapeData>>(PrepareAsyncGetAvatarFacePoseRaw(context, request, cq));
    }
    class async final :
      public StubInterface::async_interface {
     public:
      void UploadAudioClip(::grpc::ClientContext* context, const ::nvidia_ace::a2f_authoring::v1::AudioClip* request, ::nvidia_ace::a2f_authoring::v1::AudioClipHandle* response, std::function<void(::grpc::Status)>) override;
      void UploadAudioClip(::grpc::ClientContext* context, const ::nvidia_ace::a2f_authoring::v1::AudioClip* request, ::nvidia_ace::a2f_authoring::v1::AudioClipHandle* response, ::grpc::ClientUnaryReactor* reactor) override;
      void GetAvatarFacePose(::grpc::ClientContext* context, const ::nvidia_ace::a2f_authoring::v1::FacePoseRequest* request, ::nvidia_ace::a2f_authoring::v1::BlendShapeData* response, std::function<void(::grpc::Status)>) override;
      void GetAvatarFacePose(::grpc::ClientContext* context, const ::nvidia_ace::a2f_authoring::v1::FacePoseRequest* request, ::nvidia_ace::a2f_authoring::v1::BlendShapeData* response, ::grpc::ClientUnaryReactor* reactor) override;
     private:
      friend class Stub;
      explicit async(Stub* stub): stub_(stub) { }
      Stub* stub() { return stub_; }
      Stub* stub_;
    };
    class async* async() override { return &async_stub_; }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    class async async_stub_{this};
    ::grpc::ClientAsyncResponseReader< ::nvidia_ace::a2f_authoring::v1::AudioClipHandle>* AsyncUploadAudioClipRaw(::grpc::ClientContext* context, const ::nvidia_ace::a2f_authoring::v1::AudioClip& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::nvidia_ace::a2f_authoring::v1::AudioClipHandle>* PrepareAsyncUploadAudioClipRaw(::grpc::ClientContext* context, const ::nvidia_ace::a2f_authoring::v1::AudioClip& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::nvidia_ace::a2f_authoring::v1::BlendShapeData>* AsyncGetAvatarFacePoseRaw(::grpc::ClientContext* context, const ::nvidia_ace::a2f_authoring::v1::FacePoseRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::nvidia_ace::a2f_authoring::v1::BlendShapeData>* PrepareAsyncGetAvatarFacePoseRaw(::grpc::ClientContext* context, const ::nvidia_ace::a2f_authoring::v1::FacePoseRequest& request, ::grpc::CompletionQueue* cq) override;
    const ::grpc::internal::RpcMethod rpcmethod_UploadAudioClip_;
    const ::grpc::internal::RpcMethod rpcmethod_GetAvatarFacePose_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    // Upload the audio clip to the AuthoringService to be processed.
    virtual ::grpc::Status UploadAudioClip(::grpc::ServerContext* context, const ::nvidia_ace::a2f_authoring::v1::AudioClip* request, ::nvidia_ace::a2f_authoring::v1::AudioClipHandle* response);
    // Request a single animation frame at the specified timecode.
    virtual ::grpc::Status GetAvatarFacePose(::grpc::ServerContext* context, const ::nvidia_ace::a2f_authoring::v1::FacePoseRequest* request, ::nvidia_ace::a2f_authoring::v1::BlendShapeData* response);
  };
  template <class BaseClass>
  class WithAsyncMethod_UploadAudioClip : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_UploadAudioClip() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_UploadAudioClip() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status UploadAudioClip(::grpc::ServerContext* /*context*/, const ::nvidia_ace::a2f_authoring::v1::AudioClip* /*request*/, ::nvidia_ace::a2f_authoring::v1::AudioClipHandle* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestUploadAudioClip(::grpc::ServerContext* context, ::nvidia_ace::a2f_authoring::v1::AudioClip* request, ::grpc::ServerAsyncResponseWriter< ::nvidia_ace::a2f_authoring::v1::AudioClipHandle>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_GetAvatarFacePose : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_GetAvatarFacePose() {
      ::grpc::Service::MarkMethodAsync(1);
    }
    ~WithAsyncMethod_GetAvatarFacePose() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetAvatarFacePose(::grpc::ServerContext* /*context*/, const ::nvidia_ace::a2f_authoring::v1::FacePoseRequest* /*request*/, ::nvidia_ace::a2f_authoring::v1::BlendShapeData* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestGetAvatarFacePose(::grpc::ServerContext* context, ::nvidia_ace::a2f_authoring::v1::FacePoseRequest* request, ::grpc::ServerAsyncResponseWriter< ::nvidia_ace::a2f_authoring::v1::BlendShapeData>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(1, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_UploadAudioClip<WithAsyncMethod_GetAvatarFacePose<Service > > AsyncService;
  template <class BaseClass>
  class WithCallbackMethod_UploadAudioClip : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_UploadAudioClip() {
      ::grpc::Service::MarkMethodCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::nvidia_ace::a2f_authoring::v1::AudioClip, ::nvidia_ace::a2f_authoring::v1::AudioClipHandle>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::nvidia_ace::a2f_authoring::v1::AudioClip* request, ::nvidia_ace::a2f_authoring::v1::AudioClipHandle* response) { return this->UploadAudioClip(context, request, response); }));}
    void SetMessageAllocatorFor_UploadAudioClip(
        ::grpc::MessageAllocator< ::nvidia_ace::a2f_authoring::v1::AudioClip, ::nvidia_ace::a2f_authoring::v1::AudioClipHandle>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(0);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::nvidia_ace::a2f_authoring::v1::AudioClip, ::nvidia_ace::a2f_authoring::v1::AudioClipHandle>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_UploadAudioClip() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status UploadAudioClip(::grpc::ServerContext* /*context*/, const ::nvidia_ace::a2f_authoring::v1::AudioClip* /*request*/, ::nvidia_ace::a2f_authoring::v1::AudioClipHandle* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* UploadAudioClip(
      ::grpc::CallbackServerContext* /*context*/, const ::nvidia_ace::a2f_authoring::v1::AudioClip* /*request*/, ::nvidia_ace::a2f_authoring::v1::AudioClipHandle* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithCallbackMethod_GetAvatarFacePose : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_GetAvatarFacePose() {
      ::grpc::Service::MarkMethodCallback(1,
          new ::grpc::internal::CallbackUnaryHandler< ::nvidia_ace::a2f_authoring::v1::FacePoseRequest, ::nvidia_ace::a2f_authoring::v1::BlendShapeData>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::nvidia_ace::a2f_authoring::v1::FacePoseRequest* request, ::nvidia_ace::a2f_authoring::v1::BlendShapeData* response) { return this->GetAvatarFacePose(context, request, response); }));}
    void SetMessageAllocatorFor_GetAvatarFacePose(
        ::grpc::MessageAllocator< ::nvidia_ace::a2f_authoring::v1::FacePoseRequest, ::nvidia_ace::a2f_authoring::v1::BlendShapeData>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(1);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::nvidia_ace::a2f_authoring::v1::FacePoseRequest, ::nvidia_ace::a2f_authoring::v1::BlendShapeData>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_GetAvatarFacePose() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetAvatarFacePose(::grpc::ServerContext* /*context*/, const ::nvidia_ace::a2f_authoring::v1::FacePoseRequest* /*request*/, ::nvidia_ace::a2f_authoring::v1::BlendShapeData* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* GetAvatarFacePose(
      ::grpc::CallbackServerContext* /*context*/, const ::nvidia_ace::a2f_authoring::v1::FacePoseRequest* /*request*/, ::nvidia_ace::a2f_authoring::v1::BlendShapeData* /*response*/)  { return nullptr; }
  };
  typedef WithCallbackMethod_UploadAudioClip<WithCallbackMethod_GetAvatarFacePose<Service > > CallbackService;
  typedef CallbackService ExperimentalCallbackService;
  template <class BaseClass>
  class WithGenericMethod_UploadAudioClip : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_UploadAudioClip() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_UploadAudioClip() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status UploadAudioClip(::grpc::ServerContext* /*context*/, const ::nvidia_ace::a2f_authoring::v1::AudioClip* /*request*/, ::nvidia_ace::a2f_authoring::v1::AudioClipHandle* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_GetAvatarFacePose : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_GetAvatarFacePose() {
      ::grpc::Service::MarkMethodGeneric(1);
    }
    ~WithGenericMethod_GetAvatarFacePose() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetAvatarFacePose(::grpc::ServerContext* /*context*/, const ::nvidia_ace::a2f_authoring::v1::FacePoseRequest* /*request*/, ::nvidia_ace::a2f_authoring::v1::BlendShapeData* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithRawMethod_UploadAudioClip : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_UploadAudioClip() {
      ::grpc::Service::MarkMethodRaw(0);
    }
    ~WithRawMethod_UploadAudioClip() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status UploadAudioClip(::grpc::ServerContext* /*context*/, const ::nvidia_ace::a2f_authoring::v1::AudioClip* /*request*/, ::nvidia_ace::a2f_authoring::v1::AudioClipHandle* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestUploadAudioClip(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawMethod_GetAvatarFacePose : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_GetAvatarFacePose() {
      ::grpc::Service::MarkMethodRaw(1);
    }
    ~WithRawMethod_GetAvatarFacePose() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetAvatarFacePose(::grpc::ServerContext* /*context*/, const ::nvidia_ace::a2f_authoring::v1::FacePoseRequest* /*request*/, ::nvidia_ace::a2f_authoring::v1::BlendShapeData* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestGetAvatarFacePose(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(1, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_UploadAudioClip : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_UploadAudioClip() {
      ::grpc::Service::MarkMethodRawCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->UploadAudioClip(context, request, response); }));
    }
    ~WithRawCallbackMethod_UploadAudioClip() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status UploadAudioClip(::grpc::ServerContext* /*context*/, const ::nvidia_ace::a2f_authoring::v1::AudioClip* /*request*/, ::nvidia_ace::a2f_authoring::v1::AudioClipHandle* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* UploadAudioClip(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_GetAvatarFacePose : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_GetAvatarFacePose() {
      ::grpc::Service::MarkMethodRawCallback(1,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->GetAvatarFacePose(context, request, response); }));
    }
    ~WithRawCallbackMethod_GetAvatarFacePose() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetAvatarFacePose(::grpc::ServerContext* /*context*/, const ::nvidia_ace::a2f_authoring::v1::FacePoseRequest* /*request*/, ::nvidia_ace::a2f_authoring::v1::BlendShapeData* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* GetAvatarFacePose(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_UploadAudioClip : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_UploadAudioClip() {
      ::grpc::Service::MarkMethodStreamed(0,
        new ::grpc::internal::StreamedUnaryHandler<
          ::nvidia_ace::a2f_authoring::v1::AudioClip, ::nvidia_ace::a2f_authoring::v1::AudioClipHandle>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::nvidia_ace::a2f_authoring::v1::AudioClip, ::nvidia_ace::a2f_authoring::v1::AudioClipHandle>* streamer) {
                       return this->StreamedUploadAudioClip(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_UploadAudioClip() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status UploadAudioClip(::grpc::ServerContext* /*context*/, const ::nvidia_ace::a2f_authoring::v1::AudioClip* /*request*/, ::nvidia_ace::a2f_authoring::v1::AudioClipHandle* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedUploadAudioClip(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::nvidia_ace::a2f_authoring::v1::AudioClip,::nvidia_ace::a2f_authoring::v1::AudioClipHandle>* server_unary_streamer) = 0;
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_GetAvatarFacePose : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_GetAvatarFacePose() {
      ::grpc::Service::MarkMethodStreamed(1,
        new ::grpc::internal::StreamedUnaryHandler<
          ::nvidia_ace::a2f_authoring::v1::FacePoseRequest, ::nvidia_ace::a2f_authoring::v1::BlendShapeData>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::nvidia_ace::a2f_authoring::v1::FacePoseRequest, ::nvidia_ace::a2f_authoring::v1::BlendShapeData>* streamer) {
                       return this->StreamedGetAvatarFacePose(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_GetAvatarFacePose() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status GetAvatarFacePose(::grpc::ServerContext* /*context*/, const ::nvidia_ace::a2f_authoring::v1::FacePoseRequest* /*request*/, ::nvidia_ace::a2f_authoring::v1::BlendShapeData* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedGetAvatarFacePose(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::nvidia_ace::a2f_authoring::v1::FacePoseRequest,::nvidia_ace::a2f_authoring::v1::BlendShapeData>* server_unary_streamer) = 0;
  };
  typedef WithStreamedUnaryMethod_UploadAudioClip<WithStreamedUnaryMethod_GetAvatarFacePose<Service > > StreamedUnaryService;
  typedef Service SplitStreamedService;
  typedef WithStreamedUnaryMethod_UploadAudioClip<WithStreamedUnaryMethod_GetAvatarFacePose<Service > > StreamedService;
};

}  // namespace v1
}  // namespace a2f_authoring
}  // namespace services
}  // namespace nvidia_ace


#endif  // GRPC_nvidia_5face_2eservices_2ea2f_5fauthoring_2ev1_2eproto__INCLUDED
