// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: nvidia_ace.services.animation_data.v1.proto
#ifndef GRPC_nvidia_5face_2eservices_2eanimation_5fdata_2ev1_2eproto__INCLUDED
#define GRPC_nvidia_5face_2eservices_2eanimation_5fdata_2ev1_2eproto__INCLUDED

#include "nvidia_ace.services.animation_data.v1.pb.h"

#include <functional>
#include <grpcpp/generic/async_generic_service.h>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/client_context.h>
#include <grpcpp/completion_queue.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/proto_utils.h>
#include <grpcpp/impl/rpc_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/support/status.h>
#include <grpcpp/support/stub_options.h>
#include <grpcpp/support/sync_stream.h>

namespace nvidia_ace {
namespace services {
namespace animation_data {
namespace v1 {

// 2 RPC exist to provide a stream of animation data
// The RPC to implement depends on if the part of the service
// is a client or a server.
// E.g.: In the case of Animation Graph Microservice, we implement both RPCs.
// One to receive and one to send.
class AnimationDataService final {
 public:
  static constexpr char const* service_full_name() {
    return "nvidia_ace.services.animation_data.v1.AnimationDataService";
  }
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    // When the service creating the animation data is a client from the service receiving them
    // This push RPC must be used.
    // An example for that is Audio2Face Microservice creating animation data and sending them
    // to Animation Graph Microservice
    std::unique_ptr< ::grpc::ClientWriterInterface< ::nvidia_ace::animation_data::v1::AnimationDataStream>> PushAnimationDataStream(::grpc::ClientContext* context, ::nvidia_ace::status::v1::Status* response) {
      return std::unique_ptr< ::grpc::ClientWriterInterface< ::nvidia_ace::animation_data::v1::AnimationDataStream>>(PushAnimationDataStreamRaw(context, response));
    }
    std::unique_ptr< ::grpc::ClientAsyncWriterInterface< ::nvidia_ace::animation_data::v1::AnimationDataStream>> AsyncPushAnimationDataStream(::grpc::ClientContext* context, ::nvidia_ace::status::v1::Status* response, ::grpc::CompletionQueue* cq, void* tag) {
      return std::unique_ptr< ::grpc::ClientAsyncWriterInterface< ::nvidia_ace::animation_data::v1::AnimationDataStream>>(AsyncPushAnimationDataStreamRaw(context, response, cq, tag));
    }
    std::unique_ptr< ::grpc::ClientAsyncWriterInterface< ::nvidia_ace::animation_data::v1::AnimationDataStream>> PrepareAsyncPushAnimationDataStream(::grpc::ClientContext* context, ::nvidia_ace::status::v1::Status* response, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncWriterInterface< ::nvidia_ace::animation_data::v1::AnimationDataStream>>(PrepareAsyncPushAnimationDataStreamRaw(context, response, cq));
    }
    // When the service creating the animation data is a server from the service receiving them
    // This pull RPC must be used.
    // An example for that is the Omniverse Renderer Microservice requesting animation data to the
    // Animation Graph Microservice.
    std::unique_ptr< ::grpc::ClientReaderInterface< ::nvidia_ace::animation_data::v1::AnimationDataStream>> PullAnimationDataStream(::grpc::ClientContext* context, const ::nvidia_ace::animation_id::v1::AnimationIds& request) {
      return std::unique_ptr< ::grpc::ClientReaderInterface< ::nvidia_ace::animation_data::v1::AnimationDataStream>>(PullAnimationDataStreamRaw(context, request));
    }
    std::unique_ptr< ::grpc::ClientAsyncReaderInterface< ::nvidia_ace::animation_data::v1::AnimationDataStream>> AsyncPullAnimationDataStream(::grpc::ClientContext* context, const ::nvidia_ace::animation_id::v1::AnimationIds& request, ::grpc::CompletionQueue* cq, void* tag) {
      return std::unique_ptr< ::grpc::ClientAsyncReaderInterface< ::nvidia_ace::animation_data::v1::AnimationDataStream>>(AsyncPullAnimationDataStreamRaw(context, request, cq, tag));
    }
    std::unique_ptr< ::grpc::ClientAsyncReaderInterface< ::nvidia_ace::animation_data::v1::AnimationDataStream>> PrepareAsyncPullAnimationDataStream(::grpc::ClientContext* context, const ::nvidia_ace::animation_id::v1::AnimationIds& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncReaderInterface< ::nvidia_ace::animation_data::v1::AnimationDataStream>>(PrepareAsyncPullAnimationDataStreamRaw(context, request, cq));
    }
    class async_interface {
     public:
      virtual ~async_interface() {}
      // When the service creating the animation data is a client from the service receiving them
      // This push RPC must be used.
      // An example for that is Audio2Face Microservice creating animation data and sending them
      // to Animation Graph Microservice
      virtual void PushAnimationDataStream(::grpc::ClientContext* context, ::nvidia_ace::status::v1::Status* response, ::grpc::ClientWriteReactor< ::nvidia_ace::animation_data::v1::AnimationDataStream>* reactor) = 0;
      // When the service creating the animation data is a server from the service receiving them
      // This pull RPC must be used.
      // An example for that is the Omniverse Renderer Microservice requesting animation data to the
      // Animation Graph Microservice.
      virtual void PullAnimationDataStream(::grpc::ClientContext* context, const ::nvidia_ace::animation_id::v1::AnimationIds* request, ::grpc::ClientReadReactor< ::nvidia_ace::animation_data::v1::AnimationDataStream>* reactor) = 0;
    };
    typedef class async_interface experimental_async_interface;
    virtual class async_interface* async() { return nullptr; }
    class async_interface* experimental_async() { return async(); }
   private:
    virtual ::grpc::ClientWriterInterface< ::nvidia_ace::animation_data::v1::AnimationDataStream>* PushAnimationDataStreamRaw(::grpc::ClientContext* context, ::nvidia_ace::status::v1::Status* response) = 0;
    virtual ::grpc::ClientAsyncWriterInterface< ::nvidia_ace::animation_data::v1::AnimationDataStream>* AsyncPushAnimationDataStreamRaw(::grpc::ClientContext* context, ::nvidia_ace::status::v1::Status* response, ::grpc::CompletionQueue* cq, void* tag) = 0;
    virtual ::grpc::ClientAsyncWriterInterface< ::nvidia_ace::animation_data::v1::AnimationDataStream>* PrepareAsyncPushAnimationDataStreamRaw(::grpc::ClientContext* context, ::nvidia_ace::status::v1::Status* response, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientReaderInterface< ::nvidia_ace::animation_data::v1::AnimationDataStream>* PullAnimationDataStreamRaw(::grpc::ClientContext* context, const ::nvidia_ace::animation_id::v1::AnimationIds& request) = 0;
    virtual ::grpc::ClientAsyncReaderInterface< ::nvidia_ace::animation_data::v1::AnimationDataStream>* AsyncPullAnimationDataStreamRaw(::grpc::ClientContext* context, const ::nvidia_ace::animation_id::v1::AnimationIds& request, ::grpc::CompletionQueue* cq, void* tag) = 0;
    virtual ::grpc::ClientAsyncReaderInterface< ::nvidia_ace::animation_data::v1::AnimationDataStream>* PrepareAsyncPullAnimationDataStreamRaw(::grpc::ClientContext* context, const ::nvidia_ace::animation_id::v1::AnimationIds& request, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());
    std::unique_ptr< ::grpc::ClientWriter< ::nvidia_ace::animation_data::v1::AnimationDataStream>> PushAnimationDataStream(::grpc::ClientContext* context, ::nvidia_ace::status::v1::Status* response) {
      return std::unique_ptr< ::grpc::ClientWriter< ::nvidia_ace::animation_data::v1::AnimationDataStream>>(PushAnimationDataStreamRaw(context, response));
    }
    std::unique_ptr< ::grpc::ClientAsyncWriter< ::nvidia_ace::animation_data::v1::AnimationDataStream>> AsyncPushAnimationDataStream(::grpc::ClientContext* context, ::nvidia_ace::status::v1::Status* response, ::grpc::CompletionQueue* cq, void* tag) {
      return std::unique_ptr< ::grpc::ClientAsyncWriter< ::nvidia_ace::animation_data::v1::AnimationDataStream>>(AsyncPushAnimationDataStreamRaw(context, response, cq, tag));
    }
    std::unique_ptr< ::grpc::ClientAsyncWriter< ::nvidia_ace::animation_data::v1::AnimationDataStream>> PrepareAsyncPushAnimationDataStream(::grpc::ClientContext* context, ::nvidia_ace::status::v1::Status* response, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncWriter< ::nvidia_ace::animation_data::v1::AnimationDataStream>>(PrepareAsyncPushAnimationDataStreamRaw(context, response, cq));
    }
    std::unique_ptr< ::grpc::ClientReader< ::nvidia_ace::animation_data::v1::AnimationDataStream>> PullAnimationDataStream(::grpc::ClientContext* context, const ::nvidia_ace::animation_id::v1::AnimationIds& request) {
      return std::unique_ptr< ::grpc::ClientReader< ::nvidia_ace::animation_data::v1::AnimationDataStream>>(PullAnimationDataStreamRaw(context, request));
    }
    std::unique_ptr< ::grpc::ClientAsyncReader< ::nvidia_ace::animation_data::v1::AnimationDataStream>> AsyncPullAnimationDataStream(::grpc::ClientContext* context, const ::nvidia_ace::animation_id::v1::AnimationIds& request, ::grpc::CompletionQueue* cq, void* tag) {
      return std::unique_ptr< ::grpc::ClientAsyncReader< ::nvidia_ace::animation_data::v1::AnimationDataStream>>(AsyncPullAnimationDataStreamRaw(context, request, cq, tag));
    }
    std::unique_ptr< ::grpc::ClientAsyncReader< ::nvidia_ace::animation_data::v1::AnimationDataStream>> PrepareAsyncPullAnimationDataStream(::grpc::ClientContext* context, const ::nvidia_ace::animation_id::v1::AnimationIds& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncReader< ::nvidia_ace::animation_data::v1::AnimationDataStream>>(PrepareAsyncPullAnimationDataStreamRaw(context, request, cq));
    }
    class async final :
      public StubInterface::async_interface {
     public:
      void PushAnimationDataStream(::grpc::ClientContext* context, ::nvidia_ace::status::v1::Status* response, ::grpc::ClientWriteReactor< ::nvidia_ace::animation_data::v1::AnimationDataStream>* reactor) override;
      void PullAnimationDataStream(::grpc::ClientContext* context, const ::nvidia_ace::animation_id::v1::AnimationIds* request, ::grpc::ClientReadReactor< ::nvidia_ace::animation_data::v1::AnimationDataStream>* reactor) override;
     private:
      friend class Stub;
      explicit async(Stub* stub): stub_(stub) { }
      Stub* stub() { return stub_; }
      Stub* stub_;
    };
    class async* async() override { return &async_stub_; }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    class async async_stub_{this};
    ::grpc::ClientWriter< ::nvidia_ace::animation_data::v1::AnimationDataStream>* PushAnimationDataStreamRaw(::grpc::ClientContext* context, ::nvidia_ace::status::v1::Status* response) override;
    ::grpc::ClientAsyncWriter< ::nvidia_ace::animation_data::v1::AnimationDataStream>* AsyncPushAnimationDataStreamRaw(::grpc::ClientContext* context, ::nvidia_ace::status::v1::Status* response, ::grpc::CompletionQueue* cq, void* tag) override;
    ::grpc::ClientAsyncWriter< ::nvidia_ace::animation_data::v1::AnimationDataStream>* PrepareAsyncPushAnimationDataStreamRaw(::grpc::ClientContext* context, ::nvidia_ace::status::v1::Status* response, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientReader< ::nvidia_ace::animation_data::v1::AnimationDataStream>* PullAnimationDataStreamRaw(::grpc::ClientContext* context, const ::nvidia_ace::animation_id::v1::AnimationIds& request) override;
    ::grpc::ClientAsyncReader< ::nvidia_ace::animation_data::v1::AnimationDataStream>* AsyncPullAnimationDataStreamRaw(::grpc::ClientContext* context, const ::nvidia_ace::animation_id::v1::AnimationIds& request, ::grpc::CompletionQueue* cq, void* tag) override;
    ::grpc::ClientAsyncReader< ::nvidia_ace::animation_data::v1::AnimationDataStream>* PrepareAsyncPullAnimationDataStreamRaw(::grpc::ClientContext* context, const ::nvidia_ace::animation_id::v1::AnimationIds& request, ::grpc::CompletionQueue* cq) override;
    const ::grpc::internal::RpcMethod rpcmethod_PushAnimationDataStream_;
    const ::grpc::internal::RpcMethod rpcmethod_PullAnimationDataStream_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    // When the service creating the animation data is a client from the service receiving them
    // This push RPC must be used.
    // An example for that is Audio2Face Microservice creating animation data and sending them
    // to Animation Graph Microservice
    virtual ::grpc::Status PushAnimationDataStream(::grpc::ServerContext* context, ::grpc::ServerReader< ::nvidia_ace::animation_data::v1::AnimationDataStream>* reader, ::nvidia_ace::status::v1::Status* response);
    // When the service creating the animation data is a server from the service receiving them
    // This pull RPC must be used.
    // An example for that is the Omniverse Renderer Microservice requesting animation data to the
    // Animation Graph Microservice.
    virtual ::grpc::Status PullAnimationDataStream(::grpc::ServerContext* context, const ::nvidia_ace::animation_id::v1::AnimationIds* request, ::grpc::ServerWriter< ::nvidia_ace::animation_data::v1::AnimationDataStream>* writer);
  };
  template <class BaseClass>
  class WithAsyncMethod_PushAnimationDataStream : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_PushAnimationDataStream() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_PushAnimationDataStream() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status PushAnimationDataStream(::grpc::ServerContext* /*context*/, ::grpc::ServerReader< ::nvidia_ace::animation_data::v1::AnimationDataStream>* /*reader*/, ::nvidia_ace::status::v1::Status* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestPushAnimationDataStream(::grpc::ServerContext* context, ::grpc::ServerAsyncReader< ::nvidia_ace::status::v1::Status, ::nvidia_ace::animation_data::v1::AnimationDataStream>* reader, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncClientStreaming(0, context, reader, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_PullAnimationDataStream : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_PullAnimationDataStream() {
      ::grpc::Service::MarkMethodAsync(1);
    }
    ~WithAsyncMethod_PullAnimationDataStream() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status PullAnimationDataStream(::grpc::ServerContext* /*context*/, const ::nvidia_ace::animation_id::v1::AnimationIds* /*request*/, ::grpc::ServerWriter< ::nvidia_ace::animation_data::v1::AnimationDataStream>* /*writer*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestPullAnimationDataStream(::grpc::ServerContext* context, ::nvidia_ace::animation_id::v1::AnimationIds* request, ::grpc::ServerAsyncWriter< ::nvidia_ace::animation_data::v1::AnimationDataStream>* writer, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncServerStreaming(1, context, request, writer, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_PushAnimationDataStream<WithAsyncMethod_PullAnimationDataStream<Service > > AsyncService;
  template <class BaseClass>
  class WithCallbackMethod_PushAnimationDataStream : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_PushAnimationDataStream() {
      ::grpc::Service::MarkMethodCallback(0,
          new ::grpc::internal::CallbackClientStreamingHandler< ::nvidia_ace::animation_data::v1::AnimationDataStream, ::nvidia_ace::status::v1::Status>(
            [this](
                   ::grpc::CallbackServerContext* context, ::nvidia_ace::status::v1::Status* response) { return this->PushAnimationDataStream(context, response); }));
    }
    ~WithCallbackMethod_PushAnimationDataStream() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status PushAnimationDataStream(::grpc::ServerContext* /*context*/, ::grpc::ServerReader< ::nvidia_ace::animation_data::v1::AnimationDataStream>* /*reader*/, ::nvidia_ace::status::v1::Status* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerReadReactor< ::nvidia_ace::animation_data::v1::AnimationDataStream>* PushAnimationDataStream(
      ::grpc::CallbackServerContext* /*context*/, ::nvidia_ace::status::v1::Status* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithCallbackMethod_PullAnimationDataStream : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_PullAnimationDataStream() {
      ::grpc::Service::MarkMethodCallback(1,
          new ::grpc::internal::CallbackServerStreamingHandler< ::nvidia_ace::animation_id::v1::AnimationIds, ::nvidia_ace::animation_data::v1::AnimationDataStream>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::nvidia_ace::animation_id::v1::AnimationIds* request) { return this->PullAnimationDataStream(context, request); }));
    }
    ~WithCallbackMethod_PullAnimationDataStream() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status PullAnimationDataStream(::grpc::ServerContext* /*context*/, const ::nvidia_ace::animation_id::v1::AnimationIds* /*request*/, ::grpc::ServerWriter< ::nvidia_ace::animation_data::v1::AnimationDataStream>* /*writer*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerWriteReactor< ::nvidia_ace::animation_data::v1::AnimationDataStream>* PullAnimationDataStream(
      ::grpc::CallbackServerContext* /*context*/, const ::nvidia_ace::animation_id::v1::AnimationIds* /*request*/)  { return nullptr; }
  };
  typedef WithCallbackMethod_PushAnimationDataStream<WithCallbackMethod_PullAnimationDataStream<Service > > CallbackService;
  typedef CallbackService ExperimentalCallbackService;
  template <class BaseClass>
  class WithGenericMethod_PushAnimationDataStream : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_PushAnimationDataStream() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_PushAnimationDataStream() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status PushAnimationDataStream(::grpc::ServerContext* /*context*/, ::grpc::ServerReader< ::nvidia_ace::animation_data::v1::AnimationDataStream>* /*reader*/, ::nvidia_ace::status::v1::Status* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_PullAnimationDataStream : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_PullAnimationDataStream() {
      ::grpc::Service::MarkMethodGeneric(1);
    }
    ~WithGenericMethod_PullAnimationDataStream() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status PullAnimationDataStream(::grpc::ServerContext* /*context*/, const ::nvidia_ace::animation_id::v1::AnimationIds* /*request*/, ::grpc::ServerWriter< ::nvidia_ace::animation_data::v1::AnimationDataStream>* /*writer*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithRawMethod_PushAnimationDataStream : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_PushAnimationDataStream() {
      ::grpc::Service::MarkMethodRaw(0);
    }
    ~WithRawMethod_PushAnimationDataStream() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status PushAnimationDataStream(::grpc::ServerContext* /*context*/, ::grpc::ServerReader< ::nvidia_ace::animation_data::v1::AnimationDataStream>* /*reader*/, ::nvidia_ace::status::v1::Status* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestPushAnimationDataStream(::grpc::ServerContext* context, ::grpc::ServerAsyncReader< ::grpc::ByteBuffer, ::grpc::ByteBuffer>* reader, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncClientStreaming(0, context, reader, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawMethod_PullAnimationDataStream : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_PullAnimationDataStream() {
      ::grpc::Service::MarkMethodRaw(1);
    }
    ~WithRawMethod_PullAnimationDataStream() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status PullAnimationDataStream(::grpc::ServerContext* /*context*/, const ::nvidia_ace::animation_id::v1::AnimationIds* /*request*/, ::grpc::ServerWriter< ::nvidia_ace::animation_data::v1::AnimationDataStream>* /*writer*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestPullAnimationDataStream(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncWriter< ::grpc::ByteBuffer>* writer, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncServerStreaming(1, context, request, writer, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_PushAnimationDataStream : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_PushAnimationDataStream() {
      ::grpc::Service::MarkMethodRawCallback(0,
          new ::grpc::internal::CallbackClientStreamingHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, ::grpc::ByteBuffer* response) { return this->PushAnimationDataStream(context, response); }));
    }
    ~WithRawCallbackMethod_PushAnimationDataStream() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status PushAnimationDataStream(::grpc::ServerContext* /*context*/, ::grpc::ServerReader< ::nvidia_ace::animation_data::v1::AnimationDataStream>* /*reader*/, ::nvidia_ace::status::v1::Status* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerReadReactor< ::grpc::ByteBuffer>* PushAnimationDataStream(
      ::grpc::CallbackServerContext* /*context*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_PullAnimationDataStream : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_PullAnimationDataStream() {
      ::grpc::Service::MarkMethodRawCallback(1,
          new ::grpc::internal::CallbackServerStreamingHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const::grpc::ByteBuffer* request) { return this->PullAnimationDataStream(context, request); }));
    }
    ~WithRawCallbackMethod_PullAnimationDataStream() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status PullAnimationDataStream(::grpc::ServerContext* /*context*/, const ::nvidia_ace::animation_id::v1::AnimationIds* /*request*/, ::grpc::ServerWriter< ::nvidia_ace::animation_data::v1::AnimationDataStream>* /*writer*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerWriteReactor< ::grpc::ByteBuffer>* PullAnimationDataStream(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/)  { return nullptr; }
  };
  typedef Service StreamedUnaryService;
  template <class BaseClass>
  class WithSplitStreamingMethod_PullAnimationDataStream : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithSplitStreamingMethod_PullAnimationDataStream() {
      ::grpc::Service::MarkMethodStreamed(1,
        new ::grpc::internal::SplitServerStreamingHandler<
          ::nvidia_ace::animation_id::v1::AnimationIds, ::nvidia_ace::animation_data::v1::AnimationDataStream>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerSplitStreamer<
                     ::nvidia_ace::animation_id::v1::AnimationIds, ::nvidia_ace::animation_data::v1::AnimationDataStream>* streamer) {
                       return this->StreamedPullAnimationDataStream(context,
                         streamer);
                  }));
    }
    ~WithSplitStreamingMethod_PullAnimationDataStream() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status PullAnimationDataStream(::grpc::ServerContext* /*context*/, const ::nvidia_ace::animation_id::v1::AnimationIds* /*request*/, ::grpc::ServerWriter< ::nvidia_ace::animation_data::v1::AnimationDataStream>* /*writer*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with split streamed
    virtual ::grpc::Status StreamedPullAnimationDataStream(::grpc::ServerContext* context, ::grpc::ServerSplitStreamer< ::nvidia_ace::animation_id::v1::AnimationIds,::nvidia_ace::animation_data::v1::AnimationDataStream>* server_split_streamer) = 0;
  };
  typedef WithSplitStreamingMethod_PullAnimationDataStream<Service > SplitStreamedService;
  typedef WithSplitStreamingMethod_PullAnimationDataStream<Service > StreamedService;
};

}  // namespace v1
}  // namespace animation_data
}  // namespace services
}  // namespace nvidia_ace


#endif  // GRPC_nvidia_5face_2eservices_2eanimation_5fdata_2ev1_2eproto__INCLUDED
