// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: nvidia_ace.services.a2f_controller.v1.proto
#ifndef GRPC_nvidia_5face_2eservices_2ea2f_5fcontroller_2ev1_2eproto__INCLUDED
#define GRPC_nvidia_5face_2eservices_2ea2f_5fcontroller_2ev1_2eproto__INCLUDED

#include "nvidia_ace.services.a2f_controller.v1.pb.h"

#include <functional>
#include <grpcpp/generic/async_generic_service.h>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/client_context.h>
#include <grpcpp/completion_queue.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/proto_utils.h>
#include <grpcpp/impl/rpc_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/support/status.h>
#include <grpcpp/support/stub_options.h>
#include <grpcpp/support/sync_stream.h>

namespace nvidia_ace {
namespace services {
namespace a2f_controller {
namespace v1 {

class A2FControllerService final {
 public:
  static constexpr char const* service_full_name() {
    return "nvidia_ace.services.a2f_controller.v1.A2FControllerService";
  }
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    // Will process a single audio clip and answer animation data
    // in a burst.
    std::unique_ptr< ::grpc::ClientReaderWriterInterface< ::nvidia_ace::controller::v1::AudioStream, ::nvidia_ace::controller::v1::AnimationDataStream>> ProcessAudioStream(::grpc::ClientContext* context) {
      return std::unique_ptr< ::grpc::ClientReaderWriterInterface< ::nvidia_ace::controller::v1::AudioStream, ::nvidia_ace::controller::v1::AnimationDataStream>>(ProcessAudioStreamRaw(context));
    }
    std::unique_ptr< ::grpc::ClientAsyncReaderWriterInterface< ::nvidia_ace::controller::v1::AudioStream, ::nvidia_ace::controller::v1::AnimationDataStream>> AsyncProcessAudioStream(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq, void* tag) {
      return std::unique_ptr< ::grpc::ClientAsyncReaderWriterInterface< ::nvidia_ace::controller::v1::AudioStream, ::nvidia_ace::controller::v1::AnimationDataStream>>(AsyncProcessAudioStreamRaw(context, cq, tag));
    }
    std::unique_ptr< ::grpc::ClientAsyncReaderWriterInterface< ::nvidia_ace::controller::v1::AudioStream, ::nvidia_ace::controller::v1::AnimationDataStream>> PrepareAsyncProcessAudioStream(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncReaderWriterInterface< ::nvidia_ace::controller::v1::AudioStream, ::nvidia_ace::controller::v1::AnimationDataStream>>(PrepareAsyncProcessAudioStreamRaw(context, cq));
    }
    class async_interface {
     public:
      virtual ~async_interface() {}
      // Will process a single audio clip and answer animation data
      // in a burst.
      virtual void ProcessAudioStream(::grpc::ClientContext* context, ::grpc::ClientBidiReactor< ::nvidia_ace::controller::v1::AudioStream,::nvidia_ace::controller::v1::AnimationDataStream>* reactor) = 0;
    };
    typedef class async_interface experimental_async_interface;
    virtual class async_interface* async() { return nullptr; }
    class async_interface* experimental_async() { return async(); }
   private:
    virtual ::grpc::ClientReaderWriterInterface< ::nvidia_ace::controller::v1::AudioStream, ::nvidia_ace::controller::v1::AnimationDataStream>* ProcessAudioStreamRaw(::grpc::ClientContext* context) = 0;
    virtual ::grpc::ClientAsyncReaderWriterInterface< ::nvidia_ace::controller::v1::AudioStream, ::nvidia_ace::controller::v1::AnimationDataStream>* AsyncProcessAudioStreamRaw(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq, void* tag) = 0;
    virtual ::grpc::ClientAsyncReaderWriterInterface< ::nvidia_ace::controller::v1::AudioStream, ::nvidia_ace::controller::v1::AnimationDataStream>* PrepareAsyncProcessAudioStreamRaw(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());
    std::unique_ptr< ::grpc::ClientReaderWriter< ::nvidia_ace::controller::v1::AudioStream, ::nvidia_ace::controller::v1::AnimationDataStream>> ProcessAudioStream(::grpc::ClientContext* context) {
      return std::unique_ptr< ::grpc::ClientReaderWriter< ::nvidia_ace::controller::v1::AudioStream, ::nvidia_ace::controller::v1::AnimationDataStream>>(ProcessAudioStreamRaw(context));
    }
    std::unique_ptr<  ::grpc::ClientAsyncReaderWriter< ::nvidia_ace::controller::v1::AudioStream, ::nvidia_ace::controller::v1::AnimationDataStream>> AsyncProcessAudioStream(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq, void* tag) {
      return std::unique_ptr< ::grpc::ClientAsyncReaderWriter< ::nvidia_ace::controller::v1::AudioStream, ::nvidia_ace::controller::v1::AnimationDataStream>>(AsyncProcessAudioStreamRaw(context, cq, tag));
    }
    std::unique_ptr<  ::grpc::ClientAsyncReaderWriter< ::nvidia_ace::controller::v1::AudioStream, ::nvidia_ace::controller::v1::AnimationDataStream>> PrepareAsyncProcessAudioStream(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncReaderWriter< ::nvidia_ace::controller::v1::AudioStream, ::nvidia_ace::controller::v1::AnimationDataStream>>(PrepareAsyncProcessAudioStreamRaw(context, cq));
    }
    class async final :
      public StubInterface::async_interface {
     public:
      void ProcessAudioStream(::grpc::ClientContext* context, ::grpc::ClientBidiReactor< ::nvidia_ace::controller::v1::AudioStream,::nvidia_ace::controller::v1::AnimationDataStream>* reactor) override;
     private:
      friend class Stub;
      explicit async(Stub* stub): stub_(stub) { }
      Stub* stub() { return stub_; }
      Stub* stub_;
    };
    class async* async() override { return &async_stub_; }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    class async async_stub_{this};
    ::grpc::ClientReaderWriter< ::nvidia_ace::controller::v1::AudioStream, ::nvidia_ace::controller::v1::AnimationDataStream>* ProcessAudioStreamRaw(::grpc::ClientContext* context) override;
    ::grpc::ClientAsyncReaderWriter< ::nvidia_ace::controller::v1::AudioStream, ::nvidia_ace::controller::v1::AnimationDataStream>* AsyncProcessAudioStreamRaw(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq, void* tag) override;
    ::grpc::ClientAsyncReaderWriter< ::nvidia_ace::controller::v1::AudioStream, ::nvidia_ace::controller::v1::AnimationDataStream>* PrepareAsyncProcessAudioStreamRaw(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq) override;
    const ::grpc::internal::RpcMethod rpcmethod_ProcessAudioStream_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    // Will process a single audio clip and answer animation data
    // in a burst.
    virtual ::grpc::Status ProcessAudioStream(::grpc::ServerContext* context, ::grpc::ServerReaderWriter< ::nvidia_ace::controller::v1::AnimationDataStream, ::nvidia_ace::controller::v1::AudioStream>* stream);
  };
  template <class BaseClass>
  class WithAsyncMethod_ProcessAudioStream : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_ProcessAudioStream() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_ProcessAudioStream() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status ProcessAudioStream(::grpc::ServerContext* /*context*/, ::grpc::ServerReaderWriter< ::nvidia_ace::controller::v1::AnimationDataStream, ::nvidia_ace::controller::v1::AudioStream>* /*stream*/)  override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestProcessAudioStream(::grpc::ServerContext* context, ::grpc::ServerAsyncReaderWriter< ::nvidia_ace::controller::v1::AnimationDataStream, ::nvidia_ace::controller::v1::AudioStream>* stream, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncBidiStreaming(0, context, stream, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_ProcessAudioStream<Service > AsyncService;
  template <class BaseClass>
  class WithCallbackMethod_ProcessAudioStream : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_ProcessAudioStream() {
      ::grpc::Service::MarkMethodCallback(0,
          new ::grpc::internal::CallbackBidiHandler< ::nvidia_ace::controller::v1::AudioStream, ::nvidia_ace::controller::v1::AnimationDataStream>(
            [this](
                   ::grpc::CallbackServerContext* context) { return this->ProcessAudioStream(context); }));
    }
    ~WithCallbackMethod_ProcessAudioStream() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status ProcessAudioStream(::grpc::ServerContext* /*context*/, ::grpc::ServerReaderWriter< ::nvidia_ace::controller::v1::AnimationDataStream, ::nvidia_ace::controller::v1::AudioStream>* /*stream*/)  override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerBidiReactor< ::nvidia_ace::controller::v1::AudioStream, ::nvidia_ace::controller::v1::AnimationDataStream>* ProcessAudioStream(
      ::grpc::CallbackServerContext* /*context*/)
      { return nullptr; }
  };
  typedef WithCallbackMethod_ProcessAudioStream<Service > CallbackService;
  typedef CallbackService ExperimentalCallbackService;
  template <class BaseClass>
  class WithGenericMethod_ProcessAudioStream : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_ProcessAudioStream() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_ProcessAudioStream() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status ProcessAudioStream(::grpc::ServerContext* /*context*/, ::grpc::ServerReaderWriter< ::nvidia_ace::controller::v1::AnimationDataStream, ::nvidia_ace::controller::v1::AudioStream>* /*stream*/)  override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithRawMethod_ProcessAudioStream : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_ProcessAudioStream() {
      ::grpc::Service::MarkMethodRaw(0);
    }
    ~WithRawMethod_ProcessAudioStream() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status ProcessAudioStream(::grpc::ServerContext* /*context*/, ::grpc::ServerReaderWriter< ::nvidia_ace::controller::v1::AnimationDataStream, ::nvidia_ace::controller::v1::AudioStream>* /*stream*/)  override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestProcessAudioStream(::grpc::ServerContext* context, ::grpc::ServerAsyncReaderWriter< ::grpc::ByteBuffer, ::grpc::ByteBuffer>* stream, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncBidiStreaming(0, context, stream, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_ProcessAudioStream : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_ProcessAudioStream() {
      ::grpc::Service::MarkMethodRawCallback(0,
          new ::grpc::internal::CallbackBidiHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context) { return this->ProcessAudioStream(context); }));
    }
    ~WithRawCallbackMethod_ProcessAudioStream() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status ProcessAudioStream(::grpc::ServerContext* /*context*/, ::grpc::ServerReaderWriter< ::nvidia_ace::controller::v1::AnimationDataStream, ::nvidia_ace::controller::v1::AudioStream>* /*stream*/)  override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerBidiReactor< ::grpc::ByteBuffer, ::grpc::ByteBuffer>* ProcessAudioStream(
      ::grpc::CallbackServerContext* /*context*/)
      { return nullptr; }
  };
  typedef Service StreamedUnaryService;
  typedef Service SplitStreamedService;
  typedef Service StreamedService;
};

}  // namespace v1
}  // namespace a2f_controller
}  // namespace services
}  // namespace nvidia_ace


#endif  // GRPC_nvidia_5face_2eservices_2ea2f_5fcontroller_2ev1_2eproto__INCLUDED
