// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: nvidia_ace.emotion_aggregate.v1.proto
// Protobuf C++ Version: 5.26.0

#ifndef GOOGLE_PROTOBUF_INCLUDED_nvidia_5face_2eemotion_5faggregate_2ev1_2eproto_2epb_2eh
#define GOOGLE_PROTOBUF_INCLUDED_nvidia_5face_2eemotion_5faggregate_2ev1_2eproto_2epb_2eh

#include <limits>
#include <string>
#include <type_traits>
#include <utility>

#include "google/protobuf/port_def.inc"
#if PROTOBUF_VERSION != 5026000
#error "Protobuf C++ gencode is built with an incompatible version of"
#error "Protobuf C++ headers/runtime. See"
#error "https://protobuf.dev/support/cross-version-runtime-guarantee/#cpp"
#endif
#include "google/protobuf/port_undef.inc"
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/arena.h"
#include "google/protobuf/arenastring.h"
#include "google/protobuf/generated_message_tctable_decl.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/metadata_lite.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/message.h"
#include "google/protobuf/repeated_field.h"  // IWYU pragma: export
#include "google/protobuf/extension_set.h"  // IWYU pragma: export
#include "google/protobuf/unknown_field_set.h"
#include "nvidia_ace.emotion_with_timecode.v1.pb.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"

#define PROTOBUF_INTERNAL_EXPORT_nvidia_5face_2eemotion_5faggregate_2ev1_2eproto

namespace google {
namespace protobuf {
namespace internal {
class AnyMetadata;
}  // namespace internal
}  // namespace protobuf
}  // namespace google

// Internal implementation detail -- do not use these members.
struct TableStruct_nvidia_5face_2eemotion_5faggregate_2ev1_2eproto {
  static const ::uint32_t offsets[];
};
extern const ::google::protobuf::internal::DescriptorTable
    descriptor_table_nvidia_5face_2eemotion_5faggregate_2ev1_2eproto;
namespace nvidia_ace {
namespace emotion_aggregate {
namespace v1 {
class EmotionAggregate;
struct EmotionAggregateDefaultTypeInternal;
extern EmotionAggregateDefaultTypeInternal _EmotionAggregate_default_instance_;
}  // namespace v1
}  // namespace emotion_aggregate
}  // namespace nvidia_ace
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google

namespace nvidia_ace {
namespace emotion_aggregate {
namespace v1 {

// ===================================================================


// -------------------------------------------------------------------

class EmotionAggregate final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:nvidia_ace.emotion_aggregate.v1.EmotionAggregate) */ {
 public:
  inline EmotionAggregate() : EmotionAggregate(nullptr) {}
  ~EmotionAggregate() override;
  template <typename = void>
  explicit PROTOBUF_CONSTEXPR EmotionAggregate(
      ::google::protobuf::internal::ConstantInitialized);

  inline EmotionAggregate(const EmotionAggregate& from) : EmotionAggregate(nullptr, from) {}
  inline EmotionAggregate(EmotionAggregate&& from) noexcept
      : EmotionAggregate(nullptr, std::move(from)) {}
  inline EmotionAggregate& operator=(const EmotionAggregate& from) {
    CopyFrom(from);
    return *this;
  }
  inline EmotionAggregate& operator=(EmotionAggregate&& from) noexcept {
    if (this == &from) return *this;
    if (GetArena() == from.GetArena()
#ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetArena() != nullptr
#endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const EmotionAggregate& default_instance() {
    return *internal_default_instance();
  }
  static inline const EmotionAggregate* internal_default_instance() {
    return reinterpret_cast<const EmotionAggregate*>(
        &_EmotionAggregate_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 0;
  friend void swap(EmotionAggregate& a, EmotionAggregate& b) { a.Swap(&b); }
  inline void Swap(EmotionAggregate* other) {
    if (other == this) return;
#ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetArena() != nullptr && GetArena() == other->GetArena()) {
#else   // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetArena() == other->GetArena()) {
#endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(EmotionAggregate* other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  EmotionAggregate* New(::google::protobuf::Arena* arena = nullptr) const final {
    return ::google::protobuf::Message::DefaultConstruct<EmotionAggregate>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const EmotionAggregate& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const EmotionAggregate& from) { EmotionAggregate::MergeImpl(*this, from); }

  private:
  static void MergeImpl(
      ::google::protobuf::MessageLite& to_msg,
      const ::google::protobuf::MessageLite& from_msg);

  public:
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  ::size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::google::protobuf::internal::ParseContext* ctx) final;
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* arena);
  void SharedDtor();
  void InternalSwap(EmotionAggregate* other);
 private:
  friend class ::google::protobuf::internal::AnyMetadata;
  static ::absl::string_view FullMessageName() { return "nvidia_ace.emotion_aggregate.v1.EmotionAggregate"; }

 protected:
  explicit EmotionAggregate(::google::protobuf::Arena* arena);
  EmotionAggregate(::google::protobuf::Arena* arena, const EmotionAggregate& from);
  EmotionAggregate(::google::protobuf::Arena* arena, EmotionAggregate&& from) noexcept
      : EmotionAggregate(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::MessageLite::ClassData* GetClassData()
      const final;

 public:
  ::google::protobuf::Metadata GetMetadata() const final;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kInputEmotionsFieldNumber = 1,
    kA2EOutputFieldNumber = 2,
    kA2FSmoothedOutputFieldNumber = 3,
  };
  // repeated .nvidia_ace.emotion_with_timecode.v1.EmotionWithTimeCode input_emotions = 1;
  int input_emotions_size() const;
  private:
  int _internal_input_emotions_size() const;

  public:
  void clear_input_emotions() ;
  ::nvidia_ace::emotion_with_timecode::v1::EmotionWithTimeCode* mutable_input_emotions(int index);
  ::google::protobuf::RepeatedPtrField<::nvidia_ace::emotion_with_timecode::v1::EmotionWithTimeCode>* mutable_input_emotions();

  private:
  const ::google::protobuf::RepeatedPtrField<::nvidia_ace::emotion_with_timecode::v1::EmotionWithTimeCode>& _internal_input_emotions() const;
  ::google::protobuf::RepeatedPtrField<::nvidia_ace::emotion_with_timecode::v1::EmotionWithTimeCode>* _internal_mutable_input_emotions();
  public:
  const ::nvidia_ace::emotion_with_timecode::v1::EmotionWithTimeCode& input_emotions(int index) const;
  ::nvidia_ace::emotion_with_timecode::v1::EmotionWithTimeCode* add_input_emotions();
  const ::google::protobuf::RepeatedPtrField<::nvidia_ace::emotion_with_timecode::v1::EmotionWithTimeCode>& input_emotions() const;
  // repeated .nvidia_ace.emotion_with_timecode.v1.EmotionWithTimeCode a2e_output = 2;
  int a2e_output_size() const;
  private:
  int _internal_a2e_output_size() const;

  public:
  void clear_a2e_output() ;
  ::nvidia_ace::emotion_with_timecode::v1::EmotionWithTimeCode* mutable_a2e_output(int index);
  ::google::protobuf::RepeatedPtrField<::nvidia_ace::emotion_with_timecode::v1::EmotionWithTimeCode>* mutable_a2e_output();

  private:
  const ::google::protobuf::RepeatedPtrField<::nvidia_ace::emotion_with_timecode::v1::EmotionWithTimeCode>& _internal_a2e_output() const;
  ::google::protobuf::RepeatedPtrField<::nvidia_ace::emotion_with_timecode::v1::EmotionWithTimeCode>* _internal_mutable_a2e_output();
  public:
  const ::nvidia_ace::emotion_with_timecode::v1::EmotionWithTimeCode& a2e_output(int index) const;
  ::nvidia_ace::emotion_with_timecode::v1::EmotionWithTimeCode* add_a2e_output();
  const ::google::protobuf::RepeatedPtrField<::nvidia_ace::emotion_with_timecode::v1::EmotionWithTimeCode>& a2e_output() const;
  // repeated .nvidia_ace.emotion_with_timecode.v1.EmotionWithTimeCode a2f_smoothed_output = 3;
  int a2f_smoothed_output_size() const;
  private:
  int _internal_a2f_smoothed_output_size() const;

  public:
  void clear_a2f_smoothed_output() ;
  ::nvidia_ace::emotion_with_timecode::v1::EmotionWithTimeCode* mutable_a2f_smoothed_output(int index);
  ::google::protobuf::RepeatedPtrField<::nvidia_ace::emotion_with_timecode::v1::EmotionWithTimeCode>* mutable_a2f_smoothed_output();

  private:
  const ::google::protobuf::RepeatedPtrField<::nvidia_ace::emotion_with_timecode::v1::EmotionWithTimeCode>& _internal_a2f_smoothed_output() const;
  ::google::protobuf::RepeatedPtrField<::nvidia_ace::emotion_with_timecode::v1::EmotionWithTimeCode>* _internal_mutable_a2f_smoothed_output();
  public:
  const ::nvidia_ace::emotion_with_timecode::v1::EmotionWithTimeCode& a2f_smoothed_output(int index) const;
  ::nvidia_ace::emotion_with_timecode::v1::EmotionWithTimeCode* add_a2f_smoothed_output();
  const ::google::protobuf::RepeatedPtrField<::nvidia_ace::emotion_with_timecode::v1::EmotionWithTimeCode>& a2f_smoothed_output() const;
  // @@protoc_insertion_point(class_scope:nvidia_ace.emotion_aggregate.v1.EmotionAggregate)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<
      2, 3, 3,
      0, 2>
      _table_;
  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(
        ::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena);
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena, const Impl_& from);
    ::google::protobuf::RepeatedPtrField< ::nvidia_ace::emotion_with_timecode::v1::EmotionWithTimeCode > input_emotions_;
    ::google::protobuf::RepeatedPtrField< ::nvidia_ace::emotion_with_timecode::v1::EmotionWithTimeCode > a2e_output_;
    ::google::protobuf::RepeatedPtrField< ::nvidia_ace::emotion_with_timecode::v1::EmotionWithTimeCode > a2f_smoothed_output_;
    mutable ::google::protobuf::internal::CachedSize _cached_size_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_nvidia_5face_2eemotion_5faggregate_2ev1_2eproto;
};

// ===================================================================




// ===================================================================


#ifdef __GNUC__
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// -------------------------------------------------------------------

// EmotionAggregate

// repeated .nvidia_ace.emotion_with_timecode.v1.EmotionWithTimeCode input_emotions = 1;
inline int EmotionAggregate::_internal_input_emotions_size() const {
  return _internal_input_emotions().size();
}
inline int EmotionAggregate::input_emotions_size() const {
  return _internal_input_emotions_size();
}
inline ::nvidia_ace::emotion_with_timecode::v1::EmotionWithTimeCode* EmotionAggregate::mutable_input_emotions(int index)
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_mutable:nvidia_ace.emotion_aggregate.v1.EmotionAggregate.input_emotions)
  return _internal_mutable_input_emotions()->Mutable(index);
}
inline ::google::protobuf::RepeatedPtrField<::nvidia_ace::emotion_with_timecode::v1::EmotionWithTimeCode>* EmotionAggregate::mutable_input_emotions()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_mutable_list:nvidia_ace.emotion_aggregate.v1.EmotionAggregate.input_emotions)
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  return _internal_mutable_input_emotions();
}
inline const ::nvidia_ace::emotion_with_timecode::v1::EmotionWithTimeCode& EmotionAggregate::input_emotions(int index) const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:nvidia_ace.emotion_aggregate.v1.EmotionAggregate.input_emotions)
  return _internal_input_emotions().Get(index);
}
inline ::nvidia_ace::emotion_with_timecode::v1::EmotionWithTimeCode* EmotionAggregate::add_input_emotions() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ::nvidia_ace::emotion_with_timecode::v1::EmotionWithTimeCode* _add = _internal_mutable_input_emotions()->Add();
  // @@protoc_insertion_point(field_add:nvidia_ace.emotion_aggregate.v1.EmotionAggregate.input_emotions)
  return _add;
}
inline const ::google::protobuf::RepeatedPtrField<::nvidia_ace::emotion_with_timecode::v1::EmotionWithTimeCode>& EmotionAggregate::input_emotions() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_list:nvidia_ace.emotion_aggregate.v1.EmotionAggregate.input_emotions)
  return _internal_input_emotions();
}
inline const ::google::protobuf::RepeatedPtrField<::nvidia_ace::emotion_with_timecode::v1::EmotionWithTimeCode>&
EmotionAggregate::_internal_input_emotions() const {
  PROTOBUF_TSAN_READ(&_impl_._tsan_detect_race);
  return _impl_.input_emotions_;
}
inline ::google::protobuf::RepeatedPtrField<::nvidia_ace::emotion_with_timecode::v1::EmotionWithTimeCode>*
EmotionAggregate::_internal_mutable_input_emotions() {
  PROTOBUF_TSAN_READ(&_impl_._tsan_detect_race);
  return &_impl_.input_emotions_;
}

// repeated .nvidia_ace.emotion_with_timecode.v1.EmotionWithTimeCode a2e_output = 2;
inline int EmotionAggregate::_internal_a2e_output_size() const {
  return _internal_a2e_output().size();
}
inline int EmotionAggregate::a2e_output_size() const {
  return _internal_a2e_output_size();
}
inline ::nvidia_ace::emotion_with_timecode::v1::EmotionWithTimeCode* EmotionAggregate::mutable_a2e_output(int index)
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_mutable:nvidia_ace.emotion_aggregate.v1.EmotionAggregate.a2e_output)
  return _internal_mutable_a2e_output()->Mutable(index);
}
inline ::google::protobuf::RepeatedPtrField<::nvidia_ace::emotion_with_timecode::v1::EmotionWithTimeCode>* EmotionAggregate::mutable_a2e_output()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_mutable_list:nvidia_ace.emotion_aggregate.v1.EmotionAggregate.a2e_output)
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  return _internal_mutable_a2e_output();
}
inline const ::nvidia_ace::emotion_with_timecode::v1::EmotionWithTimeCode& EmotionAggregate::a2e_output(int index) const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:nvidia_ace.emotion_aggregate.v1.EmotionAggregate.a2e_output)
  return _internal_a2e_output().Get(index);
}
inline ::nvidia_ace::emotion_with_timecode::v1::EmotionWithTimeCode* EmotionAggregate::add_a2e_output() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ::nvidia_ace::emotion_with_timecode::v1::EmotionWithTimeCode* _add = _internal_mutable_a2e_output()->Add();
  // @@protoc_insertion_point(field_add:nvidia_ace.emotion_aggregate.v1.EmotionAggregate.a2e_output)
  return _add;
}
inline const ::google::protobuf::RepeatedPtrField<::nvidia_ace::emotion_with_timecode::v1::EmotionWithTimeCode>& EmotionAggregate::a2e_output() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_list:nvidia_ace.emotion_aggregate.v1.EmotionAggregate.a2e_output)
  return _internal_a2e_output();
}
inline const ::google::protobuf::RepeatedPtrField<::nvidia_ace::emotion_with_timecode::v1::EmotionWithTimeCode>&
EmotionAggregate::_internal_a2e_output() const {
  PROTOBUF_TSAN_READ(&_impl_._tsan_detect_race);
  return _impl_.a2e_output_;
}
inline ::google::protobuf::RepeatedPtrField<::nvidia_ace::emotion_with_timecode::v1::EmotionWithTimeCode>*
EmotionAggregate::_internal_mutable_a2e_output() {
  PROTOBUF_TSAN_READ(&_impl_._tsan_detect_race);
  return &_impl_.a2e_output_;
}

// repeated .nvidia_ace.emotion_with_timecode.v1.EmotionWithTimeCode a2f_smoothed_output = 3;
inline int EmotionAggregate::_internal_a2f_smoothed_output_size() const {
  return _internal_a2f_smoothed_output().size();
}
inline int EmotionAggregate::a2f_smoothed_output_size() const {
  return _internal_a2f_smoothed_output_size();
}
inline ::nvidia_ace::emotion_with_timecode::v1::EmotionWithTimeCode* EmotionAggregate::mutable_a2f_smoothed_output(int index)
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_mutable:nvidia_ace.emotion_aggregate.v1.EmotionAggregate.a2f_smoothed_output)
  return _internal_mutable_a2f_smoothed_output()->Mutable(index);
}
inline ::google::protobuf::RepeatedPtrField<::nvidia_ace::emotion_with_timecode::v1::EmotionWithTimeCode>* EmotionAggregate::mutable_a2f_smoothed_output()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_mutable_list:nvidia_ace.emotion_aggregate.v1.EmotionAggregate.a2f_smoothed_output)
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  return _internal_mutable_a2f_smoothed_output();
}
inline const ::nvidia_ace::emotion_with_timecode::v1::EmotionWithTimeCode& EmotionAggregate::a2f_smoothed_output(int index) const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:nvidia_ace.emotion_aggregate.v1.EmotionAggregate.a2f_smoothed_output)
  return _internal_a2f_smoothed_output().Get(index);
}
inline ::nvidia_ace::emotion_with_timecode::v1::EmotionWithTimeCode* EmotionAggregate::add_a2f_smoothed_output() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ::nvidia_ace::emotion_with_timecode::v1::EmotionWithTimeCode* _add = _internal_mutable_a2f_smoothed_output()->Add();
  // @@protoc_insertion_point(field_add:nvidia_ace.emotion_aggregate.v1.EmotionAggregate.a2f_smoothed_output)
  return _add;
}
inline const ::google::protobuf::RepeatedPtrField<::nvidia_ace::emotion_with_timecode::v1::EmotionWithTimeCode>& EmotionAggregate::a2f_smoothed_output() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_list:nvidia_ace.emotion_aggregate.v1.EmotionAggregate.a2f_smoothed_output)
  return _internal_a2f_smoothed_output();
}
inline const ::google::protobuf::RepeatedPtrField<::nvidia_ace::emotion_with_timecode::v1::EmotionWithTimeCode>&
EmotionAggregate::_internal_a2f_smoothed_output() const {
  PROTOBUF_TSAN_READ(&_impl_._tsan_detect_race);
  return _impl_.a2f_smoothed_output_;
}
inline ::google::protobuf::RepeatedPtrField<::nvidia_ace::emotion_with_timecode::v1::EmotionWithTimeCode>*
EmotionAggregate::_internal_mutable_a2f_smoothed_output() {
  PROTOBUF_TSAN_READ(&_impl_._tsan_detect_race);
  return &_impl_.a2f_smoothed_output_;
}

#ifdef __GNUC__
#pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)
}  // namespace v1
}  // namespace emotion_aggregate
}  // namespace nvidia_ace


// @@protoc_insertion_point(global_scope)

#include "google/protobuf/port_undef.inc"

#endif  // GOOGLE_PROTOBUF_INCLUDED_nvidia_5face_2eemotion_5faggregate_2ev1_2eproto_2epb_2eh
