// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: nvidia_ace.a2f.v1.proto

#ifndef GRPC_MOCK_nvidia_5face_2ea2f_2ev1_2eproto__INCLUDED
#define GRPC_MOCK_nvidia_5face_2ea2f_2ev1_2eproto__INCLUDED

#include "nvidia_ace.a2f.v1.pb.h"
#include "nvidia_ace.a2f.v1.grpc.pb.h"

#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/sync_stream.h>
#include <gmock/gmock.h>
namespace nvidia_ace {
namespace a2f {
namespace v1 {

}  // namespace v1
}  // namespace a2f
}  // namespace nvidia_ace


#endif  // GRPC_MOCK_nvidia_5face_2ea2f_2ev1_2eproto__INCLUDED
