// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: nvidia_ace.services.a2f.v1.proto

#ifndef GRPC_MOCK_nvidia_5face_2eservices_2ea2f_2ev1_2eproto__INCLUDED
#define GRPC_MOCK_nvidia_5face_2eservices_2ea2f_2ev1_2eproto__INCLUDED

#include "nvidia_ace.services.a2f.v1.pb.h"
#include "nvidia_ace.services.a2f.v1.grpc.pb.h"

#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/sync_stream.h>
#include <gmock/gmock.h>
namespace nvidia_ace {
namespace services {
namespace a2f {
namespace v1 {

class MockA2FServiceStub : public A2FService::StubInterface {
 public:
  MOCK_METHOD2(PushAudioStreamRaw, ::grpc::ClientWriterInterface< ::nvidia_ace::a2f::v1::AudioStream>*(::grpc::ClientContext* context, ::nvidia_ace::status::v1::Status* response));
  MOCK_METHOD4(AsyncPushAudioStreamRaw, ::grpc::ClientAsyncWriterInterface< ::nvidia_ace::a2f::v1::AudioStream>*(::grpc::ClientContext* context, ::nvidia_ace::status::v1::Status* response, ::grpc::CompletionQueue* cq, void* tag));
  MOCK_METHOD3(PrepareAsyncPushAudioStreamRaw, ::grpc::ClientAsyncWriterInterface< ::nvidia_ace::a2f::v1::AudioStream>*(::grpc::ClientContext* context, ::nvidia_ace::status::v1::Status* response, ::grpc::CompletionQueue* cq));
};

}  // namespace v1
}  // namespace a2f
}  // namespace services
}  // namespace nvidia_ace


#endif  // GRPC_MOCK_nvidia_5face_2eservices_2ea2f_2ev1_2eproto__INCLUDED
