// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: nvidia_ace.animation_id.v1.proto
// Protobuf C++ Version: 5.26.0

#include "nvidia_ace.animation_id.v1.pb.h"

#include <algorithm>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/descriptor.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/reflection_ops.h"
#include "google/protobuf/wire_format.h"
#include "google/protobuf/generated_message_tctable_impl.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::google::protobuf;
namespace _pbi = ::google::protobuf::internal;
namespace _fl = ::google::protobuf::internal::field_layout;
namespace nvidia_ace {
namespace animation_id {
namespace v1 {

inline constexpr AnimationIds::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : request_id_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        stream_id_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        target_object_id_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR AnimationIds::AnimationIds(::_pbi::ConstantInitialized)
    : _impl_(::_pbi::ConstantInitialized()) {}
struct AnimationIdsDefaultTypeInternal {
  PROTOBUF_CONSTEXPR AnimationIdsDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~AnimationIdsDefaultTypeInternal() {}
  union {
    AnimationIds _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 AnimationIdsDefaultTypeInternal _AnimationIds_default_instance_;
}  // namespace v1
}  // namespace animation_id
}  // namespace nvidia_ace
static ::_pb::Metadata file_level_metadata_nvidia_5face_2eanimation_5fid_2ev1_2eproto[1];
static constexpr const ::_pb::EnumDescriptor**
    file_level_enum_descriptors_nvidia_5face_2eanimation_5fid_2ev1_2eproto = nullptr;
static constexpr const ::_pb::ServiceDescriptor**
    file_level_service_descriptors_nvidia_5face_2eanimation_5fid_2ev1_2eproto = nullptr;
const ::uint32_t
    TableStruct_nvidia_5face_2eanimation_5fid_2ev1_2eproto::offsets[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
        protodesc_cold) = {
        ~0u,  // no _has_bits_
        PROTOBUF_FIELD_OFFSET(::nvidia_ace::animation_id::v1::AnimationIds, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::nvidia_ace::animation_id::v1::AnimationIds, _impl_.request_id_),
        PROTOBUF_FIELD_OFFSET(::nvidia_ace::animation_id::v1::AnimationIds, _impl_.stream_id_),
        PROTOBUF_FIELD_OFFSET(::nvidia_ace::animation_id::v1::AnimationIds, _impl_.target_object_id_),
};

static const ::_pbi::MigrationSchema
    schemas[] ABSL_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
        {0, -1, -1, sizeof(::nvidia_ace::animation_id::v1::AnimationIds)},
};
static const ::_pb::Message* const file_default_instances[] = {
    &::nvidia_ace::animation_id::v1::_AnimationIds_default_instance_._instance,
};
const char descriptor_table_protodef_nvidia_5face_2eanimation_5fid_2ev1_2eproto[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
    protodesc_cold) = {
    "\n nvidia_ace.animation_id.v1.proto\022\032nvid"
    "ia_ace.animation_id.v1\"O\n\014AnimationIds\022\022"
    "\n\nrequest_id\030\001 \001(\t\022\021\n\tstream_id\030\002 \001(\t\022\030\n"
    "\020target_object_id\030\003 \001(\tb\006proto3"
};
static ::absl::once_flag descriptor_table_nvidia_5face_2eanimation_5fid_2ev1_2eproto_once;
const ::_pbi::DescriptorTable descriptor_table_nvidia_5face_2eanimation_5fid_2ev1_2eproto = {
    false,
    false,
    151,
    descriptor_table_protodef_nvidia_5face_2eanimation_5fid_2ev1_2eproto,
    "nvidia_ace.animation_id.v1.proto",
    &descriptor_table_nvidia_5face_2eanimation_5fid_2ev1_2eproto_once,
    nullptr,
    0,
    1,
    schemas,
    file_default_instances,
    TableStruct_nvidia_5face_2eanimation_5fid_2ev1_2eproto::offsets,
    file_level_metadata_nvidia_5face_2eanimation_5fid_2ev1_2eproto,
    file_level_enum_descriptors_nvidia_5face_2eanimation_5fid_2ev1_2eproto,
    file_level_service_descriptors_nvidia_5face_2eanimation_5fid_2ev1_2eproto,
};

// This function exists to be marked as weak.
// It can significantly speed up compilation by breaking up LLVM's SCC
// in the .pb.cc translation units. Large translation units see a
// reduction of more than 35% of walltime for optimized builds. Without
// the weak attribute all the messages in the file, including all the
// vtables and everything they use become part of the same SCC through
// a cycle like:
// GetMetadata -> descriptor table -> default instances ->
//   vtables -> GetMetadata
// By adding a weak function here we break the connection from the
// individual vtables back into the descriptor table.
PROTOBUF_ATTRIBUTE_WEAK const ::_pbi::DescriptorTable* descriptor_table_nvidia_5face_2eanimation_5fid_2ev1_2eproto_getter() {
  return &descriptor_table_nvidia_5face_2eanimation_5fid_2ev1_2eproto;
}
namespace nvidia_ace {
namespace animation_id {
namespace v1 {
// ===================================================================

class AnimationIds::_Internal {
 public:
};

AnimationIds::AnimationIds(::google::protobuf::Arena* arena)
    : ::google::protobuf::Message(arena) {
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:nvidia_ace.animation_id.v1.AnimationIds)
}
inline PROTOBUF_NDEBUG_INLINE AnimationIds::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from)
      : request_id_(arena, from.request_id_),
        stream_id_(arena, from.stream_id_),
        target_object_id_(arena, from.target_object_id_),
        _cached_size_{0} {}

AnimationIds::AnimationIds(
    ::google::protobuf::Arena* arena,
    const AnimationIds& from)
    : ::google::protobuf::Message(arena) {
  AnimationIds* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_);

  // @@protoc_insertion_point(copy_constructor:nvidia_ace.animation_id.v1.AnimationIds)
}
inline PROTOBUF_NDEBUG_INLINE AnimationIds::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : request_id_(arena),
        stream_id_(arena),
        target_object_id_(arena),
        _cached_size_{0} {}

inline void AnimationIds::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
}
AnimationIds::~AnimationIds() {
  // @@protoc_insertion_point(destructor:nvidia_ace.animation_id.v1.AnimationIds)
  _internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  SharedDtor();
}
inline void AnimationIds::SharedDtor() {
  ABSL_DCHECK(GetArena() == nullptr);
  _impl_.request_id_.Destroy();
  _impl_.stream_id_.Destroy();
  _impl_.target_object_id_.Destroy();
  _impl_.~Impl_();
}

const ::google::protobuf::MessageLite::ClassData*
AnimationIds::GetClassData() const {
  PROTOBUF_CONSTINIT static const ::google::protobuf::MessageLite::
      ClassDataFull _data_ = {
          {
              nullptr,  // OnDemandRegisterArenaDtor
              PROTOBUF_FIELD_OFFSET(AnimationIds, _impl_._cached_size_),
              false,
          },
          &AnimationIds::MergeImpl,
          &AnimationIds::kDescriptorMethods,
      };
  return &_data_;
}
PROTOBUF_NOINLINE void AnimationIds::Clear() {
// @@protoc_insertion_point(message_clear_start:nvidia_ace.animation_id.v1.AnimationIds)
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.request_id_.ClearToEmpty();
  _impl_.stream_id_.ClearToEmpty();
  _impl_.target_object_id_.ClearToEmpty();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

const char* AnimationIds::_InternalParse(
    const char* ptr, ::_pbi::ParseContext* ctx) {
  ptr = ::_pbi::TcParser::ParseLoop(this, ptr, ctx, &_table_.header);
  return ptr;
}


PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<2, 3, 0, 83, 2> AnimationIds::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    3, 24,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967288,  // skipmap
    offsetof(decltype(_table_), field_entries),
    3,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    &_AnimationIds_default_instance_._instance,
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::nvidia_ace::animation_id::v1::AnimationIds>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    {::_pbi::TcParser::MiniParse, {}},
    // string request_id = 1;
    {::_pbi::TcParser::FastUS1,
     {10, 63, 0, PROTOBUF_FIELD_OFFSET(AnimationIds, _impl_.request_id_)}},
    // string stream_id = 2;
    {::_pbi::TcParser::FastUS1,
     {18, 63, 0, PROTOBUF_FIELD_OFFSET(AnimationIds, _impl_.stream_id_)}},
    // string target_object_id = 3;
    {::_pbi::TcParser::FastUS1,
     {26, 63, 0, PROTOBUF_FIELD_OFFSET(AnimationIds, _impl_.target_object_id_)}},
  }}, {{
    65535, 65535
  }}, {{
    // string request_id = 1;
    {PROTOBUF_FIELD_OFFSET(AnimationIds, _impl_.request_id_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
    // string stream_id = 2;
    {PROTOBUF_FIELD_OFFSET(AnimationIds, _impl_.stream_id_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
    // string target_object_id = 3;
    {PROTOBUF_FIELD_OFFSET(AnimationIds, _impl_.target_object_id_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
  }},
  // no aux_entries
  {{
    "\47\12\11\20\0\0\0\0"
    "nvidia_ace.animation_id.v1.AnimationIds"
    "request_id"
    "stream_id"
    "target_object_id"
  }},
};

::uint8_t* AnimationIds::_InternalSerialize(
    ::uint8_t* target,
    ::google::protobuf::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:nvidia_ace.animation_id.v1.AnimationIds)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  // string request_id = 1;
  if (!this->_internal_request_id().empty()) {
    const std::string& _s = this->_internal_request_id();
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
        _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "nvidia_ace.animation_id.v1.AnimationIds.request_id");
    target = stream->WriteStringMaybeAliased(1, _s, target);
  }

  // string stream_id = 2;
  if (!this->_internal_stream_id().empty()) {
    const std::string& _s = this->_internal_stream_id();
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
        _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "nvidia_ace.animation_id.v1.AnimationIds.stream_id");
    target = stream->WriteStringMaybeAliased(2, _s, target);
  }

  // string target_object_id = 3;
  if (!this->_internal_target_object_id().empty()) {
    const std::string& _s = this->_internal_target_object_id();
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
        _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "nvidia_ace.animation_id.v1.AnimationIds.target_object_id");
    target = stream->WriteStringMaybeAliased(3, _s, target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:nvidia_ace.animation_id.v1.AnimationIds)
  return target;
}

::size_t AnimationIds::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:nvidia_ace.animation_id.v1.AnimationIds)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // string request_id = 1;
  if (!this->_internal_request_id().empty()) {
    total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                    this->_internal_request_id());
  }

  // string stream_id = 2;
  if (!this->_internal_stream_id().empty()) {
    total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                    this->_internal_stream_id());
  }

  // string target_object_id = 3;
  if (!this->_internal_target_object_id().empty()) {
    total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                    this->_internal_target_object_id());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}


void AnimationIds::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<AnimationIds*>(&to_msg);
  auto& from = static_cast<const AnimationIds&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:nvidia_ace.animation_id.v1.AnimationIds)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_request_id().empty()) {
    _this->_internal_set_request_id(from._internal_request_id());
  }
  if (!from._internal_stream_id().empty()) {
    _this->_internal_set_stream_id(from._internal_stream_id());
  }
  if (!from._internal_target_object_id().empty()) {
    _this->_internal_set_target_object_id(from._internal_target_object_id());
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void AnimationIds::CopyFrom(const AnimationIds& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:nvidia_ace.animation_id.v1.AnimationIds)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

PROTOBUF_NOINLINE bool AnimationIds::IsInitialized() const {
  return true;
}

void AnimationIds::InternalSwap(AnimationIds* PROTOBUF_RESTRICT other) {
  using std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.request_id_, &other->_impl_.request_id_, arena);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.stream_id_, &other->_impl_.stream_id_, arena);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.target_object_id_, &other->_impl_.target_object_id_, arena);
}

::google::protobuf::Metadata AnimationIds::GetMetadata() const {
  return ::_pbi::AssignDescriptors(&descriptor_table_nvidia_5face_2eanimation_5fid_2ev1_2eproto_getter,
                                   &descriptor_table_nvidia_5face_2eanimation_5fid_2ev1_2eproto_once,
                                   file_level_metadata_nvidia_5face_2eanimation_5fid_2ev1_2eproto[0]);
}
// @@protoc_insertion_point(namespace_scope)
}  // namespace v1
}  // namespace animation_id
}  // namespace nvidia_ace
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google
// @@protoc_insertion_point(global_scope)
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2
static ::std::false_type _static_init_ PROTOBUF_UNUSED =
    (::_pbi::AddDescriptors(&descriptor_table_nvidia_5face_2eanimation_5fid_2ev1_2eproto),
     ::std::false_type{});
#include "google/protobuf/port_undef.inc"
