// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: version.proto

#include "version.pb.h"
#include "version.grpc.pb.h"

#include <functional>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/impl/channel_interface.h>
#include <grpcpp/impl/client_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/rpc_service_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/support/sync_stream.h>
namespace nvidia_ace {
namespace services {
namespace version {
namespace v1 {

static const char* VersionInformationService_method_names[] = {
  "/nvidia_ace.services.version.v1.VersionInformationService/GetVersionInformation",
};

std::unique_ptr< VersionInformationService::Stub> VersionInformationService::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< VersionInformationService::Stub> stub(new VersionInformationService::Stub(channel, options));
  return stub;
}

VersionInformationService::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options)
  : channel_(channel), rpcmethod_GetVersionInformation_(VersionInformationService_method_names[0], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  {}

::grpc::Status VersionInformationService::Stub::GetVersionInformation(::grpc::ClientContext* context, const ::google::protobuf::Empty& request, ::nvidia_ace::services::version::v1::VersionInformation* response) {
  return ::grpc::internal::BlockingUnaryCall< ::google::protobuf::Empty, ::nvidia_ace::services::version::v1::VersionInformation, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_GetVersionInformation_, context, request, response);
}

void VersionInformationService::Stub::async::GetVersionInformation(::grpc::ClientContext* context, const ::google::protobuf::Empty* request, ::nvidia_ace::services::version::v1::VersionInformation* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::google::protobuf::Empty, ::nvidia_ace::services::version::v1::VersionInformation, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_GetVersionInformation_, context, request, response, std::move(f));
}

void VersionInformationService::Stub::async::GetVersionInformation(::grpc::ClientContext* context, const ::google::protobuf::Empty* request, ::nvidia_ace::services::version::v1::VersionInformation* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_GetVersionInformation_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::nvidia_ace::services::version::v1::VersionInformation>* VersionInformationService::Stub::PrepareAsyncGetVersionInformationRaw(::grpc::ClientContext* context, const ::google::protobuf::Empty& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::nvidia_ace::services::version::v1::VersionInformation, ::google::protobuf::Empty, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_GetVersionInformation_, context, request);
}

::grpc::ClientAsyncResponseReader< ::nvidia_ace::services::version::v1::VersionInformation>* VersionInformationService::Stub::AsyncGetVersionInformationRaw(::grpc::ClientContext* context, const ::google::protobuf::Empty& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncGetVersionInformationRaw(context, request, cq);
  result->StartCall();
  return result;
}

VersionInformationService::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      VersionInformationService_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< VersionInformationService::Service, ::google::protobuf::Empty, ::nvidia_ace::services::version::v1::VersionInformation, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](VersionInformationService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::google::protobuf::Empty* req,
             ::nvidia_ace::services::version::v1::VersionInformation* resp) {
               return service->GetVersionInformation(ctx, req, resp);
             }, this)));
}

VersionInformationService::Service::~Service() {
}

::grpc::Status VersionInformationService::Service::GetVersionInformation(::grpc::ServerContext* context, const ::google::protobuf::Empty* request, ::nvidia_ace::services::version::v1::VersionInformation* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


}  // namespace nvidia_ace
}  // namespace services
}  // namespace version
}  // namespace v1

