// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: version.proto
// Protobuf C++ Version: 5.26.0

#ifndef GOOGLE_PROTOBUF_INCLUDED_version_2eproto_2epb_2eh
#define GOOGLE_PROTOBUF_INCLUDED_version_2eproto_2epb_2eh

#include <limits>
#include <string>
#include <type_traits>
#include <utility>

#include "google/protobuf/port_def.inc"
#if PROTOBUF_VERSION != 5026000
#error "Protobuf C++ gencode is built with an incompatible version of"
#error "Protobuf C++ headers/runtime. See"
#error "https://protobuf.dev/support/cross-version-runtime-guarantee/#cpp"
#endif
#include "google/protobuf/port_undef.inc"
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/arena.h"
#include "google/protobuf/arenastring.h"
#include "google/protobuf/generated_message_tctable_decl.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/metadata_lite.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/message.h"
#include "google/protobuf/repeated_field.h"  // IWYU pragma: export
#include "google/protobuf/extension_set.h"  // IWYU pragma: export
#include "google/protobuf/unknown_field_set.h"
#include "google/protobuf/empty.pb.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"

#define PROTOBUF_INTERNAL_EXPORT_version_2eproto

namespace google {
namespace protobuf {
namespace internal {
class AnyMetadata;
}  // namespace internal
}  // namespace protobuf
}  // namespace google

// Internal implementation detail -- do not use these members.
struct TableStruct_version_2eproto {
  static const ::uint32_t offsets[];
};
extern const ::google::protobuf::internal::DescriptorTable
    descriptor_table_version_2eproto;
namespace nvidia_ace {
namespace services {
namespace version {
namespace v1 {
class VersionEntry;
struct VersionEntryDefaultTypeInternal;
extern VersionEntryDefaultTypeInternal _VersionEntry_default_instance_;
class VersionInformation;
struct VersionInformationDefaultTypeInternal;
extern VersionInformationDefaultTypeInternal _VersionInformation_default_instance_;
}  // namespace v1
}  // namespace version
}  // namespace services
}  // namespace nvidia_ace
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google

namespace nvidia_ace {
namespace services {
namespace version {
namespace v1 {

// ===================================================================


// -------------------------------------------------------------------

class VersionEntry final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:nvidia_ace.services.version.v1.VersionEntry) */ {
 public:
  inline VersionEntry() : VersionEntry(nullptr) {}
  ~VersionEntry() override;
  template <typename = void>
  explicit PROTOBUF_CONSTEXPR VersionEntry(
      ::google::protobuf::internal::ConstantInitialized);

  inline VersionEntry(const VersionEntry& from) : VersionEntry(nullptr, from) {}
  inline VersionEntry(VersionEntry&& from) noexcept
      : VersionEntry(nullptr, std::move(from)) {}
  inline VersionEntry& operator=(const VersionEntry& from) {
    CopyFrom(from);
    return *this;
  }
  inline VersionEntry& operator=(VersionEntry&& from) noexcept {
    if (this == &from) return *this;
    if (GetArena() == from.GetArena()
#ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetArena() != nullptr
#endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const VersionEntry& default_instance() {
    return *internal_default_instance();
  }
  static inline const VersionEntry* internal_default_instance() {
    return reinterpret_cast<const VersionEntry*>(
        &_VersionEntry_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 1;
  friend void swap(VersionEntry& a, VersionEntry& b) { a.Swap(&b); }
  inline void Swap(VersionEntry* other) {
    if (other == this) return;
#ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetArena() != nullptr && GetArena() == other->GetArena()) {
#else   // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetArena() == other->GetArena()) {
#endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(VersionEntry* other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  VersionEntry* New(::google::protobuf::Arena* arena = nullptr) const final {
    return ::google::protobuf::Message::DefaultConstruct<VersionEntry>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const VersionEntry& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const VersionEntry& from) { VersionEntry::MergeImpl(*this, from); }

  private:
  static void MergeImpl(
      ::google::protobuf::MessageLite& to_msg,
      const ::google::protobuf::MessageLite& from_msg);

  public:
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  ::size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::google::protobuf::internal::ParseContext* ctx) final;
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* arena);
  void SharedDtor();
  void InternalSwap(VersionEntry* other);
 private:
  friend class ::google::protobuf::internal::AnyMetadata;
  static ::absl::string_view FullMessageName() { return "nvidia_ace.services.version.v1.VersionEntry"; }

 protected:
  explicit VersionEntry(::google::protobuf::Arena* arena);
  VersionEntry(::google::protobuf::Arena* arena, const VersionEntry& from);
  VersionEntry(::google::protobuf::Arena* arena, VersionEntry&& from) noexcept
      : VersionEntry(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::MessageLite::ClassData* GetClassData()
      const final;

 public:
  ::google::protobuf::Metadata GetMetadata() const final;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kServiceNameFieldNumber = 1,
    kVersionFieldNumber = 2,
  };
  // string service_name = 1;
  void clear_service_name() ;
  const std::string& service_name() const;
  template <typename Arg_ = const std::string&, typename... Args_>
  void set_service_name(Arg_&& arg, Args_... args);
  std::string* mutable_service_name();
  PROTOBUF_NODISCARD std::string* release_service_name();
  void set_allocated_service_name(std::string* value);

  private:
  const std::string& _internal_service_name() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_service_name(
      const std::string& value);
  std::string* _internal_mutable_service_name();

  public:
  // string version = 2;
  void clear_version() ;
  const std::string& version() const;
  template <typename Arg_ = const std::string&, typename... Args_>
  void set_version(Arg_&& arg, Args_... args);
  std::string* mutable_version();
  PROTOBUF_NODISCARD std::string* release_version();
  void set_allocated_version(std::string* value);

  private:
  const std::string& _internal_version() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_version(
      const std::string& value);
  std::string* _internal_mutable_version();

  public:
  // @@protoc_insertion_point(class_scope:nvidia_ace.services.version.v1.VersionEntry)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<
      1, 2, 0,
      71, 2>
      _table_;
  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(
        ::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena);
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena, const Impl_& from);
    ::google::protobuf::internal::ArenaStringPtr service_name_;
    ::google::protobuf::internal::ArenaStringPtr version_;
    mutable ::google::protobuf::internal::CachedSize _cached_size_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_version_2eproto;
};
// -------------------------------------------------------------------

class VersionInformation final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:nvidia_ace.services.version.v1.VersionInformation) */ {
 public:
  inline VersionInformation() : VersionInformation(nullptr) {}
  ~VersionInformation() override;
  template <typename = void>
  explicit PROTOBUF_CONSTEXPR VersionInformation(
      ::google::protobuf::internal::ConstantInitialized);

  inline VersionInformation(const VersionInformation& from) : VersionInformation(nullptr, from) {}
  inline VersionInformation(VersionInformation&& from) noexcept
      : VersionInformation(nullptr, std::move(from)) {}
  inline VersionInformation& operator=(const VersionInformation& from) {
    CopyFrom(from);
    return *this;
  }
  inline VersionInformation& operator=(VersionInformation&& from) noexcept {
    if (this == &from) return *this;
    if (GetArena() == from.GetArena()
#ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetArena() != nullptr
#endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const VersionInformation& default_instance() {
    return *internal_default_instance();
  }
  static inline const VersionInformation* internal_default_instance() {
    return reinterpret_cast<const VersionInformation*>(
        &_VersionInformation_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 0;
  friend void swap(VersionInformation& a, VersionInformation& b) { a.Swap(&b); }
  inline void Swap(VersionInformation* other) {
    if (other == this) return;
#ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetArena() != nullptr && GetArena() == other->GetArena()) {
#else   // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetArena() == other->GetArena()) {
#endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(VersionInformation* other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  VersionInformation* New(::google::protobuf::Arena* arena = nullptr) const final {
    return ::google::protobuf::Message::DefaultConstruct<VersionInformation>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const VersionInformation& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const VersionInformation& from) { VersionInformation::MergeImpl(*this, from); }

  private:
  static void MergeImpl(
      ::google::protobuf::MessageLite& to_msg,
      const ::google::protobuf::MessageLite& from_msg);

  public:
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  ::size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::google::protobuf::internal::ParseContext* ctx) final;
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* arena);
  void SharedDtor();
  void InternalSwap(VersionInformation* other);
 private:
  friend class ::google::protobuf::internal::AnyMetadata;
  static ::absl::string_view FullMessageName() { return "nvidia_ace.services.version.v1.VersionInformation"; }

 protected:
  explicit VersionInformation(::google::protobuf::Arena* arena);
  VersionInformation(::google::protobuf::Arena* arena, const VersionInformation& from);
  VersionInformation(::google::protobuf::Arena* arena, VersionInformation&& from) noexcept
      : VersionInformation(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::MessageLite::ClassData* GetClassData()
      const final;

 public:
  ::google::protobuf::Metadata GetMetadata() const final;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kVersionInformationFieldNumber = 1,
  };
  // repeated .nvidia_ace.services.version.v1.VersionEntry version_information = 1;
  int version_information_size() const;
  private:
  int _internal_version_information_size() const;

  public:
  void clear_version_information() ;
  ::nvidia_ace::services::version::v1::VersionEntry* mutable_version_information(int index);
  ::google::protobuf::RepeatedPtrField<::nvidia_ace::services::version::v1::VersionEntry>* mutable_version_information();

  private:
  const ::google::protobuf::RepeatedPtrField<::nvidia_ace::services::version::v1::VersionEntry>& _internal_version_information() const;
  ::google::protobuf::RepeatedPtrField<::nvidia_ace::services::version::v1::VersionEntry>* _internal_mutable_version_information();
  public:
  const ::nvidia_ace::services::version::v1::VersionEntry& version_information(int index) const;
  ::nvidia_ace::services::version::v1::VersionEntry* add_version_information();
  const ::google::protobuf::RepeatedPtrField<::nvidia_ace::services::version::v1::VersionEntry>& version_information() const;
  // @@protoc_insertion_point(class_scope:nvidia_ace.services.version.v1.VersionInformation)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<
      0, 1, 1,
      0, 2>
      _table_;
  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(
        ::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena);
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena, const Impl_& from);
    ::google::protobuf::RepeatedPtrField< ::nvidia_ace::services::version::v1::VersionEntry > version_information_;
    mutable ::google::protobuf::internal::CachedSize _cached_size_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_version_2eproto;
};

// ===================================================================




// ===================================================================


#ifdef __GNUC__
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// -------------------------------------------------------------------

// VersionInformation

// repeated .nvidia_ace.services.version.v1.VersionEntry version_information = 1;
inline int VersionInformation::_internal_version_information_size() const {
  return _internal_version_information().size();
}
inline int VersionInformation::version_information_size() const {
  return _internal_version_information_size();
}
inline void VersionInformation::clear_version_information() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  _impl_.version_information_.Clear();
}
inline ::nvidia_ace::services::version::v1::VersionEntry* VersionInformation::mutable_version_information(int index)
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_mutable:nvidia_ace.services.version.v1.VersionInformation.version_information)
  return _internal_mutable_version_information()->Mutable(index);
}
inline ::google::protobuf::RepeatedPtrField<::nvidia_ace::services::version::v1::VersionEntry>* VersionInformation::mutable_version_information()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_mutable_list:nvidia_ace.services.version.v1.VersionInformation.version_information)
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  return _internal_mutable_version_information();
}
inline const ::nvidia_ace::services::version::v1::VersionEntry& VersionInformation::version_information(int index) const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:nvidia_ace.services.version.v1.VersionInformation.version_information)
  return _internal_version_information().Get(index);
}
inline ::nvidia_ace::services::version::v1::VersionEntry* VersionInformation::add_version_information() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ::nvidia_ace::services::version::v1::VersionEntry* _add = _internal_mutable_version_information()->Add();
  // @@protoc_insertion_point(field_add:nvidia_ace.services.version.v1.VersionInformation.version_information)
  return _add;
}
inline const ::google::protobuf::RepeatedPtrField<::nvidia_ace::services::version::v1::VersionEntry>& VersionInformation::version_information() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_list:nvidia_ace.services.version.v1.VersionInformation.version_information)
  return _internal_version_information();
}
inline const ::google::protobuf::RepeatedPtrField<::nvidia_ace::services::version::v1::VersionEntry>&
VersionInformation::_internal_version_information() const {
  PROTOBUF_TSAN_READ(&_impl_._tsan_detect_race);
  return _impl_.version_information_;
}
inline ::google::protobuf::RepeatedPtrField<::nvidia_ace::services::version::v1::VersionEntry>*
VersionInformation::_internal_mutable_version_information() {
  PROTOBUF_TSAN_READ(&_impl_._tsan_detect_race);
  return &_impl_.version_information_;
}

// -------------------------------------------------------------------

// VersionEntry

// string service_name = 1;
inline void VersionEntry::clear_service_name() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  _impl_.service_name_.ClearToEmpty();
}
inline const std::string& VersionEntry::service_name() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:nvidia_ace.services.version.v1.VersionEntry.service_name)
  return _internal_service_name();
}
template <typename Arg_, typename... Args_>
inline PROTOBUF_ALWAYS_INLINE void VersionEntry::set_service_name(Arg_&& arg,
                                                     Args_... args) {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  _impl_.service_name_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:nvidia_ace.services.version.v1.VersionEntry.service_name)
}
inline std::string* VersionEntry::mutable_service_name() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  std::string* _s = _internal_mutable_service_name();
  // @@protoc_insertion_point(field_mutable:nvidia_ace.services.version.v1.VersionEntry.service_name)
  return _s;
}
inline const std::string& VersionEntry::_internal_service_name() const {
  PROTOBUF_TSAN_READ(&_impl_._tsan_detect_race);
  return _impl_.service_name_.Get();
}
inline void VersionEntry::_internal_set_service_name(const std::string& value) {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  _impl_.service_name_.Set(value, GetArena());
}
inline std::string* VersionEntry::_internal_mutable_service_name() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  return _impl_.service_name_.Mutable( GetArena());
}
inline std::string* VersionEntry::release_service_name() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  // @@protoc_insertion_point(field_release:nvidia_ace.services.version.v1.VersionEntry.service_name)
  return _impl_.service_name_.Release();
}
inline void VersionEntry::set_allocated_service_name(std::string* value) {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  _impl_.service_name_.SetAllocated(value, GetArena());
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
        if (_impl_.service_name_.IsDefault()) {
          _impl_.service_name_.Set("", GetArena());
        }
  #endif  // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:nvidia_ace.services.version.v1.VersionEntry.service_name)
}

// string version = 2;
inline void VersionEntry::clear_version() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  _impl_.version_.ClearToEmpty();
}
inline const std::string& VersionEntry::version() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:nvidia_ace.services.version.v1.VersionEntry.version)
  return _internal_version();
}
template <typename Arg_, typename... Args_>
inline PROTOBUF_ALWAYS_INLINE void VersionEntry::set_version(Arg_&& arg,
                                                     Args_... args) {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  _impl_.version_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:nvidia_ace.services.version.v1.VersionEntry.version)
}
inline std::string* VersionEntry::mutable_version() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  std::string* _s = _internal_mutable_version();
  // @@protoc_insertion_point(field_mutable:nvidia_ace.services.version.v1.VersionEntry.version)
  return _s;
}
inline const std::string& VersionEntry::_internal_version() const {
  PROTOBUF_TSAN_READ(&_impl_._tsan_detect_race);
  return _impl_.version_.Get();
}
inline void VersionEntry::_internal_set_version(const std::string& value) {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  _impl_.version_.Set(value, GetArena());
}
inline std::string* VersionEntry::_internal_mutable_version() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  return _impl_.version_.Mutable( GetArena());
}
inline std::string* VersionEntry::release_version() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  // @@protoc_insertion_point(field_release:nvidia_ace.services.version.v1.VersionEntry.version)
  return _impl_.version_.Release();
}
inline void VersionEntry::set_allocated_version(std::string* value) {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  _impl_.version_.SetAllocated(value, GetArena());
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
        if (_impl_.version_.IsDefault()) {
          _impl_.version_.Set("", GetArena());
        }
  #endif  // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:nvidia_ace.services.version.v1.VersionEntry.version)
}

#ifdef __GNUC__
#pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)
}  // namespace v1
}  // namespace version
}  // namespace services
}  // namespace nvidia_ace


// @@protoc_insertion_point(global_scope)

#include "google/protobuf/port_undef.inc"

#endif  // GOOGLE_PROTOBUF_INCLUDED_version_2eproto_2epb_2eh
