# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: nvidia_ace.services.animation_controller.v1.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from nvidia_ace.controller import v1_pb2 as nvidia__ace_dot_controller_dot_v1__pb2
from nvidia_ace.status import v1_pb2 as nvidia__ace_dot_status_dot_v1__pb2
from nvidia_ace.animation_id import v1_pb2 as nvidia__ace_dot_animation__id_dot_v1__pb2
from nvidia_ace.animation_data import v1_pb2 as nvidia__ace_dot_animation__data_dot_v1__pb2
from nvidia_ace.a2f import v1_pb2 as nvidia__ace_dot_a2f_dot_v1__pb2
from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n1nvidia_ace.services.animation_controller.v1.proto\x12+nvidia_ace.services.animation_controller.v1\x1a\x1envidia_ace.controller.v1.proto\x1a\x1anvidia_ace.status.v1.proto\x1a nvidia_ace.animation_id.v1.proto\x1a\"nvidia_ace.animation_data.v1.proto\x1a\x17nvidia_ace.a2f.v1.proto\x1a\x1bgoogle/protobuf/empty.proto\"\xa7\x01\n\x15\x41nimationGraphRequest\x12?\n\ranimation_ids\x18\x01 \x01(\x0b\x32(.nvidia_ace.animation_id.v1.AnimationIds\x12%\n\x1d\x61nimation_graph_variable_name\x18\x02 \x01(\t\x12&\n\x1e\x61nimation_graph_variable_value\x18\x03 \x01(\t\"\x95\x01\n\x14\x41nimationIdsOrStatus\x12\x41\n\ranimation_ids\x18\x01 \x01(\x0b\x32(.nvidia_ace.animation_id.v1.AnimationIdsH\x00\x12.\n\x06status\x18\x02 \x01(\x0b\x32\x1c.nvidia_ace.status.v1.StatusH\x00\x42\n\n\x08response2\xe8\x03\n\x1a\x41nimationControllerService\x12r\n\x13RequestAnimationIds\x12\x16.google.protobuf.Empty\x1a\x41.nvidia_ace.services.animation_controller.v1.AnimationIdsOrStatus\"\x00\x12z\n\x17PullAnimationDataStream\x12(.nvidia_ace.animation_id.v1.AnimationIds\x1a\x31.nvidia_ace.animation_data.v1.AnimationDataStream\"\x00\x30\x01\x12S\n\x0fPushAudioStream\x12\x1e.nvidia_ace.a2f.v1.AudioStream\x1a\x1c.nvidia_ace.status.v1.Status\"\x00(\x01\x12\x84\x01\n\x1cUpdateAnimationGraphVariable\x12\x42.nvidia_ace.services.animation_controller.v1.AnimationGraphRequest\x1a\x1c.nvidia_ace.status.v1.Status\"\x00(\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'nvidia_ace.services.animation_controller.v1_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_ANIMATIONGRAPHREQUEST']._serialized_start=283
  _globals['_ANIMATIONGRAPHREQUEST']._serialized_end=450
  _globals['_ANIMATIONIDSORSTATUS']._serialized_start=453
  _globals['_ANIMATIONIDSORSTATUS']._serialized_end=602
  _globals['_ANIMATIONCONTROLLERSERVICE']._serialized_start=605
  _globals['_ANIMATIONCONTROLLERSERVICE']._serialized_end=1093
# @@protoc_insertion_point(module_scope)
